In [1]:
import pandas as pd

In [2]:
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [3]:
cartoes = pd.read_csv('campeonato-brasileiro-cartoes.csv')
estatisticas_completas = pd.read_csv("campeonato-brasileiro-estatisticas-full.csv")
jogos = pd.read_csv("campeonato-brasileiro-full.csv")
gols = pd.read_csv("campeonato-brasileiro-gols.csv")

In [4]:
cartoes.head()

,partida_id,rodata,clube,cartao,atleta,num_camisa,posicao,minuto
0,4607,1,Figueirense,Amarelo,Thiago Heleno,4.0,Zagueiro,44
1,4607,1,Figueirense,Amarelo,Paulo Roberto da Silva,28.0,NaN,66
2,4608,1,Internacional,Amarelo,Juan Silveira dos Santos,4.0,Zagueiro,20
3,4608,1,Vitoria,Amarelo,Vinícius Santos Silva,NaN,NaN,82
4,4608,1,Internacional,Amarelo,Andrés D'Alessandro,10.0,Meio-campo,72

In [5]:
estatisticas_completas.head()

,partida_id,rodata,clube,chutes,chutes_no_alvo,posse_de_bola,passes,precisao_passes,faltas,cartao_amarelo,cartao_vermelho,impedimentos,escanteios
0,1,1,Vasco,0,0,NaN,0,NaN,0,0,0,0,0
1,1,1,Guarani,0,0,NaN,0,NaN,0,0,0,0,0
2,2,1,Athletico-PR,0,0,NaN,0,NaN,0,0,0,0,0
3,2,1,Gremio,0,0,NaN,0,NaN,0,0,0,0,0
4,3,1,Flamengo,0,0,NaN,0,NaN,0,0,0,0,0

In [6]:
jogos.head()

,ID,rodata,data,hora,mandante,visitante,formacao_mandante,formacao_visitante,tecnico_mandante,tecnico_visitante,vencedor,arena,mandante_Placar,visitante_Placar,mandante_Estado,visitante_Estado,arrecadacao
0,1,1,29/03/2003,16:00,Guarani,Vasco,NaN,NaN,NaN,NaN,Guarani,Brinco de Ouro,4,2,SP,RJ,NaN
1,2,1,29/03/2003,16:00,Athletico-PR,Gremio,NaN,NaN,NaN,NaN,Athletico-PR,Arena da Baixada,2,0,PR,RS,NaN
2,3,1,30/03/2003,16:00,Flamengo,Coritiba,NaN,NaN,NaN,NaN,-,Maracanã,1,1,RJ,PR,NaN
3,4,1,30/03/2003,16:00,Goias,Paysandu,NaN,NaN,NaN,NaN,-,Serra Dourada,2,2,GO,PA,NaN
4,5,1,30/03/2003,16:00,Internacional,Ponte Preta,NaN,NaN,NaN,NaN,-,Beira Rio,1,1,RS,SP,NaN

In [7]:
gols.head()

,partida_id,rodata,clube,atleta,minuto,tipo_de_gol
0,4607,1,Fluminense,Rafael Sóbis,31,NaN
1,4607,1,Fluminense,Fred,45,Penalty
2,4607,1,Fluminense,Nirley da Silva Fonseca,59,Gol Contra
3,4608,1,Internacional,Charles Aránguiz,6,NaN
4,4612,1,Cruzeiro,Marcelo Moreno,90,NaN

In [8]:
print(jogos.shape)
print(estatisticas_completas.shape)
print(gols.shape)
print(cartoes.shape)

(9165, 17)
(18330, 13)
(10820, 6)
(20953, 8)

In [9]:
print(f'{jogos.isna().sum()}\n')
print(f'{estatisticas_completas.isna().sum()}\n')
print(f'{gols.isna().sum()}\n')
print(f'{cartoes.isna().sum()}')

ID                       0
rodata                   0
data                     0
hora                     0
mandante                 0
visitante                0
formacao_mandante     4975
formacao_visitante    4975
tecnico_mandante      4610
tecnico_visitante     4610
vencedor                 0
arena                    0
mandante_Placar          0
visitante_Placar         0
mandante_Estado          0
visitante_Estado         0
arrecadacao           8785
dtype: int64

partida_id             0
rodata                 0
clube                  0
chutes                 0
chutes_no_alvo         0
posse_de_bola      10762
passes                 0
precisao_passes    13066
faltas                 0
cartao_amarelo         0
cartao_vermelho        0
impedimentos           0
escanteios             0
dtype: int64

partida_id        0
rodata            0
clube             0
atleta            0
minuto            0
tipo_de_gol    9527
dtype: int64

partida_id       0
rodata           0
clube            0
cartao           0
atleta           6
num_camisa     386
posicao       1198
minuto           0
dtype: int64

In [10]:
print(jogos["rodata"].value_counts().sort_index())

rodata
1     235
2     235
3     235
4     235
5     235
6     235
7     235
8     235
9     235
10    235
11    235
12    235
13    235
14    234
15    236
16    235
17    235
18    235
19    235
20    235
21    235
22    235
23    235
24    235
25    235
26    235
27    235
28    235
29    235
30    235
31    235
32    235
33    235
34    235
35    235
36    235
37    235
38    234
39     35
40     35
41     35
42     35
43     24
44     24
45     24
46     24
Name: count, dtype: int64

In [11]:
jogos["data"] = pd.to_datetime(jogos["data"], dayfirst=True)

jogos["temporada"] = jogos["data"].dt.year

In [12]:
stats_ano = estatisticas_completas.merge(
    jogos[["ID", "temporada"]],
    left_on="partida_id",
    right_on="ID",
    how="left"
)

In [13]:
nulos_por_ano =stats_ano.groupby("temporada")[["posse_de_bola", "precisao_passes"]].apply(lambda x: x.isna().sum())

print(nulos_por_ano)

           posse_de_bola  precisao_passes
temporada
2003                1104             1104
2004                1104             1104
2005                 924              924
2006                 760              760
2007                 760              760
2008                 760              760
2009                 760              760
2010                 760              760
2011                 760              760
2012                 760              760
2013                 760              760
2014                 728              760
2015                   0              760
2016                   0              758
2017                   2              760
2018                   0                0
2019                  46               46
2020                   2                2
2021                   0                0
2022                   0                0
2023                   0                0
2024                 760              760
2025                  12                8

In [14]:
jogos_analise = jogos.copy()
stats_analise = estatisticas_completas.copy()

In [15]:
jogos_analise["data"] = pd.to_datetime(jogos_analise["data"], dayfirst=True)

In [16]:
jogos_analise["temporada"] = jogos_analise["data"].dt.year

In [17]:
temporadas = list(range(2015, 2024)) + [2025]

In [18]:
jogos_analise = jogos_analise[jogos_analise["temporada"].isin(temporadas)].copy()

In [19]:
jogos_analise.shape

(3799, 18)

In [20]:
jogos_analise['temporada'].value_counts().sort_index()

temporada
2015    380
2016    379
2017    380
2018    380
2019    380
2020    268
2021    492
2022    380
2023    380
2025    380
Name: count, dtype: int64

In [21]:
jogos_analise["temporada"] = jogos_analise["data"].dt.year

In [22]:
jogos_analise.loc[(jogos_analise["data"] <= "2021-02-28") &(jogos_analise["data"] >= "2021-01-01"),"temporada"] = 2020

In [23]:
temporadas = list(range(2015, 2024)) + [2025]

In [24]:
jogos_analise = jogos_analise[jogos_analise["temporada"].isin(temporadas)].copy()

In [25]:
jogos_analise.shape

(3799, 18)

In [26]:
jogos_analise['temporada'].value_counts().sort_index()

temporada
2015    380
2016    379
2017    380
2018    380
2019    380
2020    380
2021    380
2022    380
2023    380
2025    380
Name: count, dtype: int64

In [27]:
colunas_stats = [
    "partida_id",
    "clube",
    "chutes",
    "chutes_no_alvo",
    "posse_de_bola",
    "passes",
    "faltas",
    "cartao_amarelo",
    "cartao_vermelho",
    "impedimentos",
    "escanteios"
]

In [28]:
stats_analise = stats_analise[colunas_stats].copy()

In [29]:
stats_analise.head()

,partida_id,clube,chutes,chutes_no_alvo,posse_de_bola,passes,faltas,cartao_amarelo,cartao_vermelho,impedimentos,escanteios
0,1,Vasco,0,0,NaN,0,0,0,0,0,0
1,1,Guarani,0,0,NaN,0,0,0,0,0,0
2,2,Athletico-PR,0,0,NaN,0,0,0,0,0,0
3,2,Gremio,0,0,NaN,0,0,0,0,0,0
4,3,Flamengo,0,0,NaN,0,0,0,0,0,0

In [30]:
stats_analise.shape

(18330, 11)

In [31]:
ids_partidas = jogos_analise["ID"]

In [32]:
stats_analise = stats_analise[stats_analise["partida_id"].isin(ids_partidas)].copy()

In [33]:
stats_analise.shape

(7598, 11)

In [34]:
stats_mandante = stats_analise.merge(jogos_analise[["ID", "mandante"]],left_on=["partida_id", "clube"],right_on=["ID", "mandante"],how="inner")

In [35]:
stats_mandante.shape

(3799, 13)

In [36]:
stats_mandante.head()

,partida_id,clube,chutes,chutes_no_alvo,posse_de_bola,passes,faltas,cartao_amarelo,cartao_vermelho,impedimentos,escanteios,ID,mandante
0,4987,Chapecoense,13,0,45%,326,20,2,0,3,3,4987,Chapecoense
1,4988,Palmeiras,17,0,50%,406,20,2,0,2,11,4988,Palmeiras
2,4989,Fluminense,26,11,74%,702,9,2,0,1,5,4989,Fluminense
3,4990,Gremio,11,0,45%,401,17,3,0,2,5,4990,Gremio
4,4993,Cruzeiro,13,0,56%,487,17,3,0,4,2,4993,Cruzeiro

In [37]:
stats_visitante = stats_analise.merge(jogos_analise[["ID", "visitante"]],left_on=["partida_id", "clube"],right_on=["ID", "visitante"],how="inner")

In [38]:
stats_visitante.shape

(3799, 13)

In [39]:
stats_visitante.head()

,partida_id,clube,chutes,chutes_no_alvo,posse_de_bola,passes,faltas,cartao_amarelo,cartao_vermelho,impedimentos,escanteios,ID,visitante
0,4987,Coritiba,16,0,55%,388,21,2,0,0,5,4987,Coritiba
1,4988,Atletico-MG,10,0,50%,426,14,4,0,4,2,4988,Atletico-MG
2,4989,Joinville,3,0,26%,250,14,0,1,1,3,4989,Joinville
3,4990,Ponte Preta,17,0,55%,473,21,4,1,0,10,4990,Ponte Preta
4,4993,Corinthians,11,0,44%,391,15,1,0,2,4,4993,Corinthians

In [40]:
stats_mandante = stats_mandante.rename(
    columns={
        "chutes": "chutes_mandante",
        "chutes_no_alvo": "chutes_no_alvo_mandante",
        "posse_de_bola": "posse_mandante",
        "passes": "passes_mandante",
        "faltas": "faltas_mandante",
        "cartao_amarelo": "cartao_amarelo_mandante",
        "cartao_vermelho": "cartao_vermelho_mandante",
        "impedimentos": "impedimentos_mandante",
        "escanteios": "escanteios_mandante"
    }
)

In [41]:
stats_mandante.columns.tolist()

['partida_id',
 'clube',
 'chutes_mandante',
 'chutes_no_alvo_mandante',
 'posse_mandante',
 'passes_mandante',
 'faltas_mandante',
 'cartao_amarelo_mandante',
 'cartao_vermelho_mandante',
 'impedimentos_mandante',
 'escanteios_mandante',
 'ID',
 'mandante']

In [42]:
stats_visitante = stats_visitante.rename(
    columns={
        "chutes": "chutes_visitante",
        "chutes_no_alvo": "chutes_no_alvo_visitante",
        "posse_de_bola": "posse_visitante",
        "passes": "passes_visitante",
        "faltas": "faltas_visitante",
        "cartao_amarelo": "cartao_amarelo_visitante",
        "cartao_vermelho": "cartao_vermelho_visitante",
        "impedimentos": "impedimentos_visitante",
        "escanteios": "escanteios_visitante"
    }
)

In [43]:
stats_visitante.columns.tolist()

['partida_id',
 'clube',
 'chutes_visitante',
 'chutes_no_alvo_visitante',
 'posse_visitante',
 'passes_visitante',
 'faltas_visitante',
 'cartao_amarelo_visitante',
 'cartao_vermelho_visitante',
 'impedimentos_visitante',
 'escanteios_visitante',
 'ID',
 'visitante']

In [44]:
df_analise = jogos_analise[["ID","temporada","rodata","data","hora","mandante","visitante","mandante_Placar","visitante_Placar"]].copy()

In [45]:
df_analise = df_analise.rename(columns={"ID": "partida_id","mandante_Placar": "gols_mandante","visitante_Placar": "gols_visitante", "rodata": "rodada" })

In [46]:
df_analise.shape

(3799, 9)

In [47]:
df_analise.head()

,partida_id,temporada,rodada,data,hora,mandante,visitante,gols_mandante,gols_visitante
4986,4987,2015,1,2015-05-09,18:32,Chapecoense,Coritiba,2,1
4987,4988,2015,1,2015-05-09,18:33,Palmeiras,Atletico-MG,2,2
4988,4989,2015,1,2015-05-09,21:00,Fluminense,Joinville,1,0
4989,4990,2015,1,2015-05-10,11:00,Gremio,Ponte Preta,3,3
4990,4993,2015,1,2015-05-10,15:59,Cruzeiro,Corinthians,0,1

In [48]:
df_analise = df_analise.merge(stats_mandante[[
            "partida_id",
            "chutes_mandante",
            "chutes_no_alvo_mandante",
            "posse_mandante",
            "passes_mandante",
            "faltas_mandante",
            "cartao_amarelo_mandante",
            "cartao_vermelho_mandante",
            "impedimentos_mandante",
            "escanteios_mandante"
        ]],on="partida_id",how="left")

In [49]:
df_analise.shape

(3799, 18)

In [50]:
df_analise.head()

,partida_id,temporada,rodada,data,hora,mandante,visitante,gols_mandante,gols_visitante,chutes_mandante,chutes_no_alvo_mandante,posse_mandante,passes_mandante,faltas_mandante,cartao_amarelo_mandante,cartao_vermelho_mandante,impedimentos_mandante,escanteios_mandante
0,4987,2015,1,2015-05-09,18:32,Chapecoense,Coritiba,2,1,13,0,45%,326,20,2,0,3,3
1,4988,2015,1,2015-05-09,18:33,Palmeiras,Atletico-MG,2,2,17,0,50%,406,20,2,0,2,11
2,4989,2015,1,2015-05-09,21:00,Fluminense,Joinville,1,0,26,11,74%,702,9,2,0,1,5
3,4990,2015,1,2015-05-10,11:00,Gremio,Ponte Preta,3,3,11,0,45%,401,17,3,0,2,5
4,4993,2015,1,2015-05-10,15:59,Cruzeiro,Corinthians,0,1,13,0,56%,487,17,3,0,4,2

In [51]:
df_analise = df_analise.merge(stats_visitante[[
            "partida_id",
            "chutes_visitante",
            "chutes_no_alvo_visitante",
            "posse_visitante",
            "passes_visitante",
            "faltas_visitante",
            "cartao_amarelo_visitante",
            "cartao_vermelho_visitante",
            "impedimentos_visitante",
            "escanteios_visitante"
        ]],on="partida_id",how="left")

In [52]:
df_analise.shape

(3799, 27)

In [53]:
df_analise.columns.tolist()

['partida_id',
 'temporada',
 'rodada',
 'data',
 'hora',
 'mandante',
 'visitante',
 'gols_mandante',
 'gols_visitante',
 'chutes_mandante',
 'chutes_no_alvo_mandante',
 'posse_mandante',
 'passes_mandante',
 'faltas_mandante',
 'cartao_amarelo_mandante',
 'cartao_vermelho_mandante',
 'impedimentos_mandante',
 'escanteios_mandante',
 'chutes_visitante',
 'chutes_no_alvo_visitante',
 'posse_visitante',
 'passes_visitante',
 'faltas_visitante',
 'cartao_amarelo_visitante',
 'cartao_vermelho_visitante',
 'impedimentos_visitante',
 'escanteios_visitante']

In [54]:
df_analise.isna().sum()

partida_id                    0
temporada                     0
rodada                        0
data                          0
hora                          0
mandante                      0
visitante                     0
gols_mandante                 0
gols_visitante                0
chutes_mandante               0
chutes_no_alvo_mandante       0
posse_mandante               31
passes_mandante               0
faltas_mandante               0
cartao_amarelo_mandante       0
cartao_vermelho_mandante      0
impedimentos_mandante         0
escanteios_mandante           0
chutes_visitante              0
chutes_no_alvo_visitante      0
posse_visitante              31
passes_visitante              0
faltas_visitante              0
cartao_amarelo_visitante      0
cartao_vermelho_visitante     0
impedimentos_visitante        0
escanteios_visitante          0
dtype: int64

In [55]:
df_analise["partida_id"].duplicated().sum()

np.int64(0)

In [56]:
df_analise.head()

,partida_id,temporada,rodada,data,hora,mandante,visitante,gols_mandante,gols_visitante,chutes_mandante,...,escanteios_mandante,chutes_visitante,chutes_no_alvo_visitante,posse_visitante,passes_visitante,faltas_visitante,cartao_amarelo_visitante,cartao_vermelho_visitante,impedimentos_visitante,escanteios_visitante
0,4987,2015,1,2015-05-09,18:32,Chapecoense,Coritiba,2,1,13,...,3,16,0,55%,388,21,2,0,0,5
1,4988,2015,1,2015-05-09,18:33,Palmeiras,Atletico-MG,2,2,17,...,11,10,0,50%,426,14,4,0,4,2
2,4989,2015,1,2015-05-09,21:00,Fluminense,Joinville,1,0,26,...,5,3,0,26%,250,14,0,1,1,3
3,4990,2015,1,2015-05-10,11:00,Gremio,Ponte Preta,3,3,11,...,5,17,0,55%,473,21,4,1,0,10
4,4993,2015,1,2015-05-10,15:59,Cruzeiro,Corinthians,0,1,13,...,2,11,0,44%,391,15,1,0,2,4

In [57]:
df_analise.info()

<class 'pandas.DataFrame'>
RangeIndex: 3799 entries, 0 to 3798
Data columns (total 27 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   partida_id                 3799 non-null   int64
 1   temporada                  3799 non-null   int32
 2   rodada                     3799 non-null   int64
 3   data                       3799 non-null   datetime64[us]
 4   hora                       3799 non-null   str
 5   mandante                   3799 non-null   str
 6   visitante                  3799 non-null   str
 7   gols_mandante              3799 non-null   int64
 8   gols_visitante             3799 non-null   int64
 9   chutes_mandante            3799 non-null   int64
 10  chutes_no_alvo_mandante    3799 non-null   int64
 11  posse_mandante             3768 non-null   str
 12  passes_mandante            3799 non-null   int64
 13  faltas_mandante            3799 non-null   int64
 14  cartao_amarelo_mandante    3799 non-null   int64
 15  cartao_vermelho_mandante   3799 non-null   int64
 16  impedimentos_mandante      3799 non-null   int64
 17  escanteios_mandante        3799 non-null   int64
 18  chutes_visitante           3799 non-null   int64
 19  chutes_no_alvo_visitante   3799 non-null   int64
 20  posse_visitante            3768 non-null   str
 21  passes_visitante           3799 non-null   int64
 22  faltas_visitante           3799 non-null   int64
 23  cartao_amarelo_visitante   3799 non-null   int64
 24  cartao_vermelho_visitante  3799 non-null   int64
 25  impedimentos_visitante     3799 non-null   int64
 26  escanteios_visitante       3799 non-null   int64
dtypes: datetime64[us](1), int32(1), int64(20), str(5)
memory usage: 893.2 KB

In [58]:
problemas_mandante = df_analise[(df_analise["gols_mandante"] > 0) &(df_analise["chutes_no_alvo_mandante"] == 0)]

In [59]:
len(problemas_mandante)

578

In [60]:
problemas_mandante[["partida_id", "temporada","mandante", "visitante","gols_mandante","chutes_no_alvo_mandante"]]

,partida_id,temporada,mandante,visitante,gols_mandante,chutes_no_alvo_mandante
0,4987,2015,Chapecoense,Coritiba,2,0
1,4988,2015,Palmeiras,Atletico-MG,2,0
3,4990,2015,Gremio,Ponte Preta,3,0
5,4994,2015,Sport,Figueirense,4,0
6,4991,2015,Athletico-PR,Internacional,3,0
...,...,...,...,...,...,...
1842,6841,2019,Athletico-PR,Botafogo-RJ,1,0
1861,6849,2019,Athletico-PR,Gremio,2,0
2017,7015,2020,Atletico-MG,Vasco,4,0
2453,7443,2021,Bragantino,Atletico-MG,1,0
3152,8139,2023,Cruzeiro,Sao Paulo,1,0

In [61]:
problemas_visitante = df_analise[(df_analise["gols_visitante"] > 0) &(df_analise["chutes_no_alvo_visitante"] == 0)]

In [62]:
len(problemas_visitante)

448

In [63]:
problemas_visitante[["partida_id", "temporada","mandante","visitante","gols_visitante","chutes_no_alvo_visitante"]]

,partida_id,temporada,mandante,visitante,gols_visitante,chutes_no_alvo_visitante
0,4987,2015,Chapecoense,Coritiba,1,0
1,4988,2015,Palmeiras,Atletico-MG,2,0
3,4990,2015,Gremio,Ponte Preta,3,0
4,4993,2015,Cruzeiro,Corinthians,1,0
5,4994,2015,Sport,Figueirense,1,0
...,...,...,...,...,...,...
1794,6781,2019,Athletico-PR,Goias,1,0
1831,6820,2019,Sao Paulo,Athletico-PR,1,0
1851,6829,2019,Atletico-MG,Athletico-PR,1,0
2017,7015,2020,Atletico-MG,Vasco,1,0
2088,7081,2020,Bragantino,Santos,1,0

In [64]:
print(problemas_mandante["temporada"].value_counts().sort_index())
print()
print(problemas_visitante["temporada"].value_counts().sort_index())

temporada
2015    275
2016    286
2017      1
2019     13
2020      1
2021      1
2023      1
Name: count, dtype: int64

temporada
2015    207
2016    219
2017      1
2018      2
2019     17
2020      2
Name: count, dtype: int64

In [65]:
df_analise[df_analise["posse_mandante"].isna()]["temporada"].value_counts().sort_index()

temporada
2017     1
2019    23
2020     1
2025     6
Name: count, dtype: int64

In [66]:
df_analise[df_analise["posse_visitante"].isna()]["temporada"].value_counts().sort_index()

temporada
2017     1
2019    23
2020     1
2025     6
Name: count, dtype: int64

In [67]:
df_posse = df_analise.dropna(
    subset=["posse_mandante", "posse_visitante"]
).copy()

print(df_posse.shape)

(3768, 27)

In [68]:
print(df_posse["posse_mandante"].dtype)
print(df_posse["posse_visitante"].dtype)

str
str

In [69]:
df_posse["posse_mandante"] = (
    df_posse["posse_mandante"]
    .str.replace("%", "", regex=False)
    .astype(float)
)

df_posse["posse_visitante"] = (
    df_posse["posse_visitante"]
    .str.replace("%", "", regex=False)
    .astype(float)
)

In [70]:
print("Total de partidas:", len(df_analise))

print("\nGols:")
print("Total de gols:", 
      df_analise["gols_mandante"].sum() + df_analise["gols_visitante"].sum())

print("Média de gols por partida:",
      f"{(df_analise["gols_mandante"] + df_analise["gols_visitante"]).mean():.2f}")

print("\nResultados:")

vitorias_mandante = (
    df_analise["gols_mandante"] > df_analise["gols_visitante"]
).sum()

empates = (
    df_analise["gols_mandante"] == df_analise["gols_visitante"]
).sum()

vitorias_visitante = (
    df_analise["gols_mandante"] < df_analise["gols_visitante"]
).sum()

print("Vitórias do mandante:", vitorias_mandante)
print("Empates:", empates)
print("Vitórias do visitante:", vitorias_visitante)

print("\nPosse de bola:")
print("Média mandante:",
      f"{df_posse["posse_mandante"].mean():.2f}")

print("Média visitante:",
      f"{df_posse["posse_visitante"].mean():.2f}")

# Sugestão de gráfico: barras comparando vitórias do mandante, empates e vitórias do visitante; biblioteca: Plotly.

Total de partidas: 3799

Gols:
Total de gols: 9031
Média de gols por partida: 2.38

Resultados:
Vitórias do mandante: 1837
Empates: 1022
Vitórias do visitante: 940

Posse de bola:
Média mandante: 51.66
Média visitante: 48.34

In [71]:
df_analise["maior_posse"] = df_analise.apply(
    lambda x: "Mandante" if x["posse_mandante"] > x["posse_visitante"]
    else "Visitante" if x["posse_visitante"] > x["posse_mandante"]
    else "Empate",
    axis=1
)

print(df_analise["maior_posse"].value_counts())

maior_posse
Mandante     2149
Visitante    1603
Empate         47
Name: count, dtype: int64

In [72]:
df_analise["maior_posse"] = df_analise.apply(
    lambda x: "Sem dados" if pd.isna(x["posse_mandante"]) or pd.isna(x["posse_visitante"])
    else "Mandante" if x["posse_mandante"] > x["posse_visitante"]
    else "Visitante" if x["posse_visitante"] > x["posse_mandante"]
    else "Empate",
    axis=1
)

print(df_analise["maior_posse"].value_counts())

maior_posse
Mandante     2149
Visitante    1603
Sem dados      31
Empate         16
Name: count, dtype: int64

In [73]:
df_analise["resultado"] = df_analise.apply(
    lambda x: "Vitória mandante" if x["gols_mandante"] > x["gols_visitante"]
    else "Vitória visitante" if x["gols_visitante"] > x["gols_mandante"]
    else "Empate",
    axis=1
)

print(pd.crosstab(df_analise["maior_posse"], df_analise["resultado"]))

resultado    Empate  Vitória mandante  Vitória visitante
maior_posse
Empate            5                 7                  4
Mandante        611               926                612
Sem dados        11                11                  9
Visitante       395               893                315

In [74]:
tabela_posse = pd.crosstab(
    df_analise["maior_posse"],
    df_analise["resultado"],
    normalize="index"
) * 100

print(tabela_posse.round(2))

# Sugestão de gráfico: barras 100% empilhadas comparando quem teve maior posse com o resultado da partida; biblioteca: Plotly.

resultado    Empate  Vitória mandante  Vitória visitante
maior_posse
Empate        31.25             43.75              25.00
Mandante      28.43             43.09              28.48
Sem dados     35.48             35.48              29.03
Visitante     24.64             55.71              19.65

In [75]:
df_analise["posse_mandante_num"] = (
    df_analise["posse_mandante"]
    .str.replace("%", "", regex=False)
    .astype(float)
)

In [76]:
df_analise["posse_mandante_num"].dtype

dtype('float64')

In [77]:
df_analise["faixa_posse_mandante"] = pd.cut(
    df_analise["posse_mandante_num"],
    bins=[0, 40, 50, 60, 101],
    labels=["Menos de 40%", "40–49%", "50–59%", "60% ou mais"],
    right=False
)

print(df_analise["faixa_posse_mandante"].value_counts().sort_index())

faixa_posse_mandante
Menos de 40%     505
40–49%          1098
50–59%          1237
60% ou mais      928
Name: count, dtype: int64

In [78]:
tabela_faixas = pd.crosstab(
    df_analise["faixa_posse_mandante"],
    df_analise["resultado"],
    normalize="index"
) * 100

print(tabela_faixas.round(2))

# Sugestão de gráfico: barras 100% empilhadas mostrando os resultados por faixa de posse do mandante; biblioteca: Plotly.

resultado             Empate  Vitória mandante  Vitória visitante
faixa_posse_mandante
Menos de 40%           23.76             59.01              17.23
40–49%                 25.05             54.19              20.77
50–59%                 27.00             46.48              26.52
60% ou mais            30.39             38.58              31.03

In [79]:
vitorias_casa = (
    df_analise[df_analise["resultado"] == "Vitória mandante"]
    .groupby("mandante")
    .size()
    .sort_values(ascending=False)
)

print(vitorias_casa.head(10))

mandante
Palmeiras        123
Flamengo         120
Atletico-MG      114
Santos           105
Fluminense       102
Corinthians      101
Gremio           100
Internacional     98
Sao Paulo         98
Athletico-PR      96
dtype: int64

In [80]:
jogos_casa = df_analise.groupby("mandante").size()

taxa_vitoria_casa = (
    (vitorias_casa / jogos_casa) * 100
).sort_values(ascending=False)

print(taxa_vitoria_casa.head(10).round(2))

mandante
Palmeiras        64.74
Flamengo         63.16
Mirassol         63.16
Atletico-MG      60.00
Gremio           58.48
Internacional    57.31
Athletico-PR     56.14
Santos           55.26
Ponte Preta      54.39
Fluminense       53.68
dtype: float64

In [81]:
resumo_casa = pd.DataFrame({
    "jogos_em_casa": jogos_casa,
    "vitorias_em_casa": vitorias_casa
})

resumo_casa["taxa_vitoria"] = (
    resumo_casa["vitorias_em_casa"] /
    resumo_casa["jogos_em_casa"] * 100
)

print(resumo_casa.sort_values("taxa_vitoria", ascending=False).round(2).head(15))

               jogos_em_casa  vitorias_em_casa  taxa_vitoria
mandante
Palmeiras                190               123         64.74
Flamengo                 190               120         63.16
Mirassol                  19                12         63.16
Atletico-MG              190               114         60.00
Gremio                   171               100         58.48
Internacional            171                98         57.31
Athletico-PR             171                96         56.14
Santos                   190               105         55.26
Ponte Preta               57                31         54.39
Fluminense               190               102         53.68
Corinthians              190               101         53.16
Sao Paulo                190                98         51.58
Bahia                    133                66         49.62
Fortaleza                114                54         47.37
Bragantino                95                45         47.37

In [82]:
vitorias_casa = (
    df_analise[df_analise["resultado"] == "Vitória mandante"]
    .groupby("mandante")
    .size()
    .sort_values(ascending=False)
)

print("TOP 10 - VITÓRIAS EM CASA")
print(vitorias_casa.head(10))

# Sugestão de gráfico: barras horizontais com o Top 10 de times com mais vitórias em casa; biblioteca: Plotly.

TOP 10 - VITÓRIAS EM CASA
mandante
Palmeiras        123
Flamengo         120
Atletico-MG      114
Santos           105
Fluminense       102
Corinthians      101
Gremio           100
Internacional     98
Sao Paulo         98
Athletico-PR      96
dtype: int64

In [83]:
vitorias_fora = (
    df_analise[df_analise["resultado"] == "Vitória visitante"]
    .groupby("visitante")
    .size()
    .sort_values(ascending=False)
)

print("TOP 10 - VITÓRIAS FORA DE CASA")
print(vitorias_fora.head(10))

# Sugestão de gráfico: barras horizontais com o Top 10 de times com mais vitórias fora de casa; biblioteca: Plotly.

TOP 10 - VITÓRIAS FORA DE CASA
visitante
Flamengo         81
Palmeiras        80
Atletico-MG      60
Corinthians      54
Sao Paulo        50
Gremio           49
Fluminense       49
Santos           46
Botafogo-RJ      43
Internacional    43
dtype: int64

In [84]:
jogos_casa = df_analise.groupby("mandante").size()

taxa_vitoria_casa = (
    vitorias_casa.reindex(jogos_casa.index, fill_value=0)
    / jogos_casa
    * 100
)

print("TOP 10 - PORCENTAGEM DE VITÓRIAS EM CASA")
print(taxa_vitoria_casa.sort_values(ascending=False).head(10).round(2))

# Sugestão de gráfico: barras horizontais com o Top 10 de porcentagem de vitórias em casa; biblioteca: Plotly.

TOP 10 - PORCENTAGEM DE VITÓRIAS EM CASA
mandante
Palmeiras        64.74
Flamengo         63.16
Mirassol         63.16
Atletico-MG      60.00
Gremio           58.48
Internacional    57.31
Athletico-PR     56.14
Santos           55.26
Ponte Preta      54.39
Fluminense       53.68
dtype: float64

In [85]:
jogos_fora = df_analise.groupby("visitante").size()

taxa_vitoria_fora = (
    vitorias_fora.reindex(jogos_fora.index, fill_value=0)
    / jogos_fora
    * 100
)

print("TOP 10 - PORCENTAGEM DE VITÓRIAS FORA")
print(taxa_vitoria_fora.sort_values(ascending=False).head(10).round(2))

# Sugestão de gráfico: barras horizontais com o Top 10 de porcentagem de vitórias fora de casa; biblioteca: Plotly.

TOP 10 - PORCENTAGEM DE VITÓRIAS FORA
visitante
Flamengo       42.63
Palmeiras      42.11
Atletico-MG    31.75
Mirassol       31.58
Gremio         28.65
Corinthians    28.42
Botafogo-RJ    28.29
Cruzeiro       27.07
Sao Paulo      26.32
Cuiaba         26.32
dtype: float64

In [86]:
total_jogos = len(df_analise)

vitorias_mandante = (df_analise["resultado"] == "Vitória mandante").sum()
empates = (df_analise["resultado"] == "Empate").sum()
vitorias_visitante = (df_analise["resultado"] == "Vitória visitante").sum()

print("RESULTADO GERAL")
print(f"Vitória mandante: {vitorias_mandante} ({vitorias_mandante / total_jogos * 100:.2f}%)")
print(f"Empate: {empates} ({empates / total_jogos * 100:.2f}%)")
print(f"Vitória visitante: {vitorias_visitante} ({vitorias_visitante / total_jogos * 100:.2f}%)")

RESULTADO GERAL
Vitória mandante: 1837 (48.35%)
Empate: 1022 (26.90%)
Vitória visitante: 940 (24.74%)

In [87]:
vitorias_casa = (
    df_analise.groupby("mandante")
    .agg(
        jogos_casa=("partida_id", "count"),
        vitorias_casa=("gols_mandante", lambda x: (x > df_analise.loc[x.index, "gols_visitante"]).sum())
    )
)

vitorias_fora = (
    df_analise.groupby("visitante")
    .agg(
        jogos_fora=("partida_id", "count"),
        vitorias_fora=("gols_visitante", lambda x: (x > df_analise.loc[x.index, "gols_mandante"]).sum())
    )
)

comparacao_casa_fora = vitorias_casa.join(vitorias_fora, how="inner")

comparacao_casa_fora["%_vit_casa"] = (
    comparacao_casa_fora["vitorias_casa"] /
    comparacao_casa_fora["jogos_casa"] * 100
)

comparacao_casa_fora["%_vit__fora"] = (
    comparacao_casa_fora["vitorias_fora"] /
    comparacao_casa_fora["jogos_fora"] * 100
)

comparacao_casa_fora["diferenca"] = (
    comparacao_casa_fora["%_vit_casa"] -
    comparacao_casa_fora["%_vit__fora"]
)

comparacao_casa_fora[["%_vit_casa", "%_vit__fora", "diferenca"]] = (
    comparacao_casa_fora[["%_vit_casa", "%_vit__fora", "diferenca"]].round(2)
)

comparacao_casa_fora.sort_values("diferenca", ascending=False)

# Sugestão de gráfico: barras agrupadas comparando a porcentagem de vitórias em casa e fora por time; biblioteca: Plotly.

,jogos_casa,vitorias_casa,jogos_fora,vitorias_fora,%_vit_casa,%_vit__fora,diferenca
mandante,,,,,,,
Ponte Preta,57,31,57,7,54.39,12.28,42.11
Bahia,133,66,133,23,49.62,17.29,32.33
Internacional,171,98,171,43,57.31,25.15,32.16
Athletico-PR,171,96,171,41,56.14,23.98,32.16
Mirassol,19,12,19,6,63.16,31.58,31.58
Santa Cruz,19,7,19,1,36.84,5.26,31.58
Santos,190,105,190,46,55.26,24.21,31.05
Gremio,171,100,171,49,58.48,28.65,29.82
Atletico-MG,190,114,189,60,60.00,31.75,28.25
Fluminense,190,102,190,49,53.68,25.79,27.89
America-MG,95,38,95,12,40.00,12.63,27.37
Joinville,19,6,19,1,31.58,5.26,26.32
Sao Paulo,190,98,190,50,51.58,26.32,25.26
Corinthians,190,101,190,54,53.16,28.42,24.74
Figueirense,38,14,38,5,36.84,13.16,23.68
Palmeiras,190,123,190,80,64.74,42.11,22.63
Sport,133,52,133,22,39.10,16.54,22.56
Bragantino,95,45,95,24,47.37,25.26,22.11
Fortaleza,114,54,114,29,47.37,25.44,21.93
CSA,19,6,19,2,31.58,10.53,21.05
Flamengo,190,120,190,81,63.16,42.63,20.53
Ceara,114,43,114,20,37.72,17.54,20.18
Coritiba,114,41,114,19,35.96,16.67,19.30
Juventude,57,17,57,6,29.82,10.53,19.30
Chapecoense,113,40,114,19,35.40,16.67,18.73
Vasco,133,53,133,29,39.85,21.80,18.05
Cruzeiro,133,59,133,36,44.36,27.07,17.29
Botafogo-RJ,152,69,152,43,45.39,28.29,17.11
Goias,95,35,95,19,36.84,20.00,16.84
Vitoria,76,27,76,16,35.53,21.05,14.47
Avai,76,21,76,12,27.63,15.79,11.84
Parana,19,3,19,1,15.79,5.26,10.53
Cuiaba,57,19,57,15,33.33,26.32,7.02
Atletico-GO,76,22,76,20,28.95,26.32,2.63

In [88]:
df_analise["chutes_total"] = (
    df_analise["chutes_mandante"] +
    df_analise["chutes_visitante"]
)

df_analise["gols_total"] = (
    df_analise["gols_mandante"] +
    df_analise["gols_visitante"]
)

finalizacoes_gols = (
    df_analise.groupby("gols_total")["chutes_total"]
    .agg(["count", "mean"])
    .round(2)
)

finalizacoes_gols

# Sugestão de gráfico: linha ou barras mostrando a média de chutes conforme o total de gols da partida; biblioteca: Plotly.

            count   mean
gols_total
0             329  24.10
1             876  24.16
2             967  25.10
3             838  26.00
4             450  26.55
5             198  27.32
6              90  28.02
7              35  30.03
8              13  27.69
9               2  29.00
10              1  35.00

In [89]:
times_casa = df_analise[ ["mandante", "gols_mandante", "chutes_mandante"]].copy()
times_casa.columns = ["time", "gols", "chutes"]

times_fora = df_analise[["visitante", "gols_visitante", "chutes_visitante"]].copy()
times_fora.columns = ["time", "gols", "chutes"]

dados_times = pd.concat([times_casa, times_fora], ignore_index=True)

dados_times.head()

          time  gols  chutes
0  Chapecoense     2      13
1    Palmeiras     2      17
2   Fluminense     1      26
3       Gremio     3      11
4     Cruzeiro     0      13

In [90]:
dados_times.shape

(7598, 3)

In [91]:
estatisticas_times = (
    dados_times
    .groupby("time")
    .agg(
        jogos=("time", "count"),
        gols=("gols", "sum"),
        chutes=("chutes", "sum")
    )
)

estatisticas_times.head()

              jogos  gols  chutes
time
America-MG      190   176    2479
Athletico-PR    342   409    4159
Atletico-GO     152   150    1877
Atletico-MG     379   550    5343
Avai            152   119    1750

In [92]:
estatisticas_times.shape

(34, 3)

In [93]:
estatisticas_times["media_gols"] = (
    estatisticas_times["gols"] /
    estatisticas_times["jogos"]
)

In [94]:
estatisticas_times["media_chutes"] = (
    estatisticas_times["chutes"] /
    estatisticas_times["jogos"]
)

In [95]:
estatisticas_times["eficiencia_conversao"] = (
    estatisticas_times["gols"] /
    estatisticas_times["chutes"] * 100
)

In [96]:
top_media_gols = (
    estatisticas_times
    .sort_values("media_gols", ascending=False)
    [["jogos", "gols", "media_gols"]]
    .head(10)
)

print("TOP 10 - MAIOR MÉDIA DE GOLS POR PARTIDA")
print(top_media_gols)

# Sugestão de gráfico: barras horizontais com o Top 10 de maior média de gols por partida; biblioteca: Plotly.

TOP 10 - MAIOR MÉDIA DE GOLS POR PARTIDA
               jogos  gols  media_gols
time
Mirassol          38    63    1.657895
Flamengo         380   622    1.636842
Palmeiras        380   613    1.613158
Atletico-MG      379   550    1.451187
Gremio           342   467    1.365497
Bragantino       190   248    1.305263
Santos           380   481    1.265789
Internacional    342   422    1.233918
Corinthians      380   463    1.218421
Fluminense       380   462    1.215789

In [97]:
top_media_chutes = (
    estatisticas_times
    .sort_values("media_chutes", ascending=False)
    [["jogos", "chutes", "media_chutes"]]
    .head(10)
)

print("TOP 10 - MAIOR MÉDIA DE CHUTES POR PARTIDA")
print(top_media_chutes)

# Sugestão de gráfico: barras horizontais com o Top 10 de maior média de chutes por partida; biblioteca: Plotly.

TOP 10 - MAIOR MÉDIA DE CHUTES POR PARTIDA
             jogos  chutes  media_chutes
time
Palmeiras      380    5508     14.494737
Flamengo       380    5501     14.476316
Bragantino     190    2711     14.268421
Atletico-MG    379    5343     14.097625
Cruzeiro       266    3586     13.481203
Bahia          266    3518     13.225564
America-MG     190    2479     13.047368
Gremio         342    4441     12.985380
Sao Paulo      380    4837     12.728947
Fortaleza      228    2900     12.719298

In [98]:
top_eficiencia = (
    estatisticas_times
    .sort_values("eficiencia_conversao", ascending=False)
    [["jogos", "gols", "chutes", "eficiencia_conversao"]]
    .head(10)
)

print("TOP 10 - MAIOR EFICIÊNCIA DE CONVERSÃO")
print(top_eficiencia)

# Sugestão de gráfico: barras horizontais com o Top 10 de maior eficiência de conversão; biblioteca: Plotly.

TOP 10 - MAIOR EFICIÊNCIA DE CONVERSÃO
               jogos  gols  chutes  eficiencia_conversao
time
Mirassol          38    63     446             14.125561
Flamengo         380   622    5501             11.307035
Palmeiras        380   613    5508             11.129267
Gremio           342   467    4441             10.515650
Atletico-MG      379   550    5343             10.293842
Corinthians      380   463    4507             10.272909
Santos           380   481    4759             10.107165
Santa Cruz        38    45     451              9.977827
Athletico-PR     342   409    4159              9.834095
Internacional    342   422    4296              9.823091

In [99]:
top_media_gols = top_media_gols.round(2)
top_media_chutes = top_media_chutes.round(2)
top_eficiencia = top_eficiencia.round(2)

In [100]:
df_analise["mais_escanteios"] = df_analise.apply(
    lambda x: "Mandante" if x["escanteios_mandante"] > x["escanteios_visitante"]
    else "Visitante" if x["escanteios_visitante"] > x["escanteios_mandante"]
    else "Empate",
    axis=1
)

print(df_analise["mais_escanteios"].value_counts())

mais_escanteios
Mandante     2167
Visitante    1277
Empate        355
Name: count, dtype: int64

In [101]:
tabela_escanteios = pd.crosstab(
    df_analise["mais_escanteios"],
    df_analise["resultado"]
)

print(tabela_escanteios)

resultado        Empate  Vitória mandante  Vitória visitante
mais_escanteios
Empate              103               172                 80
Mandante            600               967                600
Visitante           319               698                260

In [102]:
tabela_escanteios_pct = pd.crosstab(
    df_analise["mais_escanteios"],
    df_analise["resultado"],
    normalize="index"
) * 100

print(tabela_escanteios_pct.round(2))

# Sugestão de gráfico: barras 100% empilhadas comparando quem teve mais escanteios com o resultado; biblioteca: Plotly.

resultado        Empate  Vitória mandante  Vitória visitante
mais_escanteios
Empate            29.01             48.45              22.54
Mandante          27.69             44.62              27.69
Visitante         24.98             54.66              20.36

In [103]:
df_analise["mais_chutes"] = df_analise.apply(
    lambda x: "Mandante" if x["chutes_mandante"] > x["chutes_visitante"]
    else "Visitante" if x["chutes_visitante"] > x["chutes_mandante"]
    else "Empate",
    axis=1
)

print(df_analise["mais_chutes"].value_counts())

mais_chutes
Mandante     2450
Visitante    1162
Empate        187
Name: count, dtype: int64

In [104]:
tabela_chutes_pct = pd.crosstab(
    df_analise["mais_chutes"],
    df_analise["resultado"],
    normalize="index"
) * 100

print(tabela_chutes_pct.round(2))

# Sugestão de gráfico: barras 100% empilhadas comparando quem teve mais chutes com o resultado; biblioteca: Plotly.

resultado    Empate  Vitória mandante  Vitória visitante
mais_chutes
Empate        25.13             49.73              25.13
Mandante      27.02             49.18              23.80
Visitante     26.94             46.39              26.68

In [105]:
df_analise["eficiencia_mandante"] = (
    df_analise["gols_mandante"] /
    df_analise["chutes_mandante"].replace(0, pd.NA)
) * 100

df_analise["eficiencia_visitante"] = (
    df_analise["gols_visitante"] /
    df_analise["chutes_visitante"].replace(0, pd.NA)
) * 100

In [106]:
df_analise["mais_eficiente"] = df_analise.apply(
    lambda x: "Sem dados" if pd.isna(x["eficiencia_mandante"]) or pd.isna(x["eficiencia_visitante"])
    else "Mandante" if x["eficiencia_mandante"] > x["eficiencia_visitante"]
    else "Visitante" if x["eficiencia_visitante"] > x["eficiencia_mandante"]
    else "Empate",
    axis=1
)

print(df_analise["mais_eficiente"].value_counts())

mais_eficiente
Mandante     1915
Visitante    1494
Empate        365
Sem dados      25
Name: count, dtype: int64

In [107]:
tabela_eficiencia_pct = pd.crosstab(
    df_analise["mais_eficiente"],
    df_analise["resultado"],
    normalize="index"
) * 100

print(tabela_eficiencia_pct.round(2))

# Sugestão de gráfico: barras 100% empilhadas comparando quem foi mais eficiente nas finalizações com o resultado; biblioteca: Plotly.

resultado       Empate  Vitória mandante  Vitória visitante
mais_eficiente
Empate           95.89              3.84               0.27
Mandante         11.23             87.62               1.15
Sem dados        28.00             36.00              36.00
Visitante        30.12              9.10              60.78

In [108]:
resumo_temporada = (
    df_analise
    .groupby("temporada")
    .agg(
        partidas=("partida_id", "count"),
        gols_mandante=("gols_mandante", "sum"),
        gols_visitante=("gols_visitante", "sum"),
        chutes_mandante=("chutes_mandante", "sum"),
        chutes_visitante=("chutes_visitante", "sum"),
        escanteios_mandante=("escanteios_mandante", "sum"),
        escanteios_visitante=("escanteios_visitante", "sum"),
        faltas_mandante=("faltas_mandante", "sum"),
        faltas_visitante=("faltas_visitante", "sum")
    )
)

In [109]:
resumo_temporada["media_gols"] = (
    resumo_temporada["gols_mandante"] +
    resumo_temporada["gols_visitante"]
) / resumo_temporada["partidas"]

resumo_temporada["media_chutes"] = (
    resumo_temporada["chutes_mandante"] +
    resumo_temporada["chutes_visitante"]
) / resumo_temporada["partidas"]

resumo_temporada["media_escanteios"] = (
    resumo_temporada["escanteios_mandante"] +
    resumo_temporada["escanteios_visitante"]
) / resumo_temporada["partidas"]

resumo_temporada["media_faltas"] = (
    resumo_temporada["faltas_mandante"] +
    resumo_temporada["faltas_visitante"]
) / resumo_temporada["partidas"]

In [110]:
vitorias_mandante_ano = (
    df_analise[df_analise["resultado"] == "Vitória mandante"]
    .groupby("temporada")
    .size()
)

resumo_temporada["pct_vitoria_mandante"] = (
    vitorias_mandante_ano /
    resumo_temporada["partidas"] * 100
)

In [113]:
resumo_temporada[
    [
        "media_gols",
        "media_chutes",
        "media_escanteios",
        "media_faltas",
    ]
].round(2)

# Gráfico sugerido: gráfico de linhas da média de gols por temporada - Plotly Express
# Gráfico sugerido: gráfico de linhas da média de chutes por temporada - Plotly Express
# Gráfico sugerido: gráfico de linhas da média de faltas por temporada - Plotly Express

           media_gols  media_chutes  media_escanteios  media_faltas
temporada
2015             2.36         24.45             10.32         29.19
2016             2.41         25.05             10.21         31.22
2017             2.43         25.47             10.64         31.41
2018             2.18         25.26             10.67         31.11
2019             2.31         25.51              9.82         27.57
2020             2.48         25.17             10.14         31.22
2021             2.22         25.42             10.21         29.92
2022             2.38         27.19             11.03         26.88
2023             2.49         27.03             10.57         28.67
2025             2.52         23.57              9.92         26.23

In [ ]:
resultados_temporada = pd.crosstab(
    df_analise["temporada"],
    df_analise["resultado"],
    normalize="index"
) * 100

resultados_temporada = resultados_temporada.round(2)

resultados_temporada

# Gráfico sugerido: gráfico de linhas com três séries (vitória do mandante, empate e vitória do visitante) por temporada - Plotly Express

resultado  Empate  Vitória mandante  Vitória visitante
temporada
2015        23.95             52.63              23.42
2016        24.80             53.30              21.90
2017        27.11             43.95              28.95
2018        28.95             53.16              17.89
2019        25.79             48.42              25.79
2020        28.42             45.00              26.58
2021        29.74             45.79              24.47
2022        28.42             44.21              27.37
2023        25.79             46.84              27.37
2025        26.05             50.26              23.68

In [114]:
distribuicao_gols = (
    df_analise["gols_total"]
    .value_counts()
    .sort_index()
)

print(distribuicao_gols)

gols_total
0     329
1     876
2     967
3     838
4     450
5     198
6      90
7      35
8      13
9       2
10      1
Name: count, dtype: int64

In [ ]:
distribuicao_gols_pct = (
    df_analise["gols_total"]
    .value_counts(normalize=True)
    .sort_index() * 100
)

print(distribuicao_gols_pct.round(2))

# Gráfico sugerido: gráfico de barras mostrando a frequência de partidas por quantidade total de gols (0 a 10), com opção de exibir valores absolutos ou percentuais - Plotly Express

gols_total
0      8.66
1     23.06
2     25.45
3     22.06
4     11.85
5      5.21
6      2.37
7      0.92
8      0.34
9      0.05
10     0.03
Name: proportion, dtype: float64

In [118]:
correlacao_chutes_gols = dados_times["chutes"].corr(
    dados_times["gols"]
)

print(f"Correlação entre chutes e gols: {correlacao_chutes_gols:.3f}")

Correlação entre chutes e gols: 0.192

In [ ]:
print(
    dados_times[["chutes", "gols"]]
    .describe()
    .round(2)
)
# Gráfico sugerido: gráfico de dispersão entre chutes e gols por equipe em cada partida, com linha de tendência - Plotly Express

        chutes     gols
count  7598.00  7598.00
mean     12.71     1.19
std       5.12     1.10
min       0.00     0.00
25%       9.00     0.00
50%      12.00     1.00
75%      16.00     2.00
max      37.00     8.00

In [ ]:
df_analise["total_vermelhos"] = (
    df_analise["cartao_vermelho_mandante"] +
    df_analise["cartao_vermelho_visitante"]
)

print(
    df_analise["total_vermelhos"]
    .value_counts()
    .sort_index()
)

# Gráfico sugerido: gráfico de barras com a distribuição da quantidade de cartões vermelhos por partida - Plotly Express

total_vermelhos
0    3012
1     640
2     125
3      14
4       6
5       1
6       1
Name: count, dtype: int64

In [122]:
condicoes = [
    (df_analise["cartao_vermelho_mandante"] == 0) &
    (df_analise["cartao_vermelho_visitante"] == 0),

    (df_analise["cartao_vermelho_mandante"] > 0) &
    (df_analise["cartao_vermelho_visitante"] == 0),

    (df_analise["cartao_vermelho_mandante"] == 0) &
    (df_analise["cartao_vermelho_visitante"] > 0),

    (df_analise["cartao_vermelho_mandante"] > 0) &
    (df_analise["cartao_vermelho_visitante"] > 0) &
    (df_analise["cartao_vermelho_mandante"] ==
     df_analise["cartao_vermelho_visitante"]),

    (df_analise["cartao_vermelho_mandante"] >
     df_analise["cartao_vermelho_visitante"]) &
    (df_analise["cartao_vermelho_visitante"] > 0),

    (df_analise["cartao_vermelho_visitante"] >
     df_analise["cartao_vermelho_mandante"]) &
    (df_analise["cartao_vermelho_mandante"] > 0)
]

categorias = [
    "Nenhuma expulsão",
    "Expulsão apenas do mandante",
    "Expulsão apenas do visitante",
    "Expulsões iguais",
    "Mais expulsões do mandante",
    "Mais expulsões do visitante"
]

df_analise["situacao_vermelhos"] = np.select(
    condicoes,
    categorias,
    default="Verificar"
)

print(df_analise["situacao_vermelhos"].value_counts())

situacao_vermelhos
Nenhuma expulsão                3012
Expulsão apenas do visitante     425
Expulsão apenas do mandante      266
Expulsões iguais                  79
Mais expulsões do visitante       10
Mais expulsões do mandante         7
Name: count, dtype: int64

In [ ]:
print(df_analise["situacao_vermelhos"].value_counts())

print(
    df_analise[
        ["cartao_vermelho_mandante",
         "cartao_vermelho_visitante",
         "situacao_vermelhos"]
    ].drop_duplicates().sort_values(
        ["cartao_vermelho_mandante", "cartao_vermelho_visitante"]
    )
)

# Gráfico sugerido: gráfico de barras mostrando a quantidade de partidas em cada situação de expulsão - Plotly Express

situacao_vermelhos
Nenhuma expulsão                3012
Expulsão apenas do visitante     425
Expulsão apenas do mandante      266
Expulsões iguais                  79
Mais expulsões do visitante       10
Mais expulsões do mandante         7
Name: count, dtype: int64
      cartao_vermelho_mandante  cartao_vermelho_visitante  \
0                            0                          0
2                            0                          1
67                           0                          2
25                           1                          0
23                           1                          1
284                          1                          2
222                          1                          3
41                           2                          0
855                          2                          1
1189                         2                          2
2923                         2                          3
1253                         3                          3

                situacao_vermelhos
0                 Nenhuma expulsão
2     Expulsão apenas do visitante
67    Expulsão apenas do visitante
25     Expulsão apenas do mandante
23                Expulsões iguais
284    Mais expulsões do visitante
222    Mais expulsões do visitante
41     Expulsão apenas do mandante
855     Mais expulsões do mandante
1189              Expulsões iguais
2923   Mais expulsões do visitante
1253              Expulsões iguais

In [124]:
tabela_vermelhos = pd.crosstab(
    df_analise["situacao_vermelhos"],
    df_analise["resultado"]
)

print(tabela_vermelhos)

resultado                     Empate  Vitória mandante  Vitória visitante
situacao_vermelhos
Expulsão apenas do mandante       80                66                120
Expulsão apenas do visitante     110               262                 53
Expulsões iguais                  31                27                 21
Mais expulsões do mandante         2                 2                  3
Mais expulsões do visitante        2                 3                  5
Nenhuma expulsão                 797              1477                738

In [ ]:
tabela_vermelhos_pct = pd.crosstab(
    df_analise["situacao_vermelhos"],
    df_analise["resultado"],
    normalize="index"
) * 100

print(tabela_vermelhos_pct.round(2))

# Gráfico sugerido: gráfico de barras empilhadas em 100% mostrando vitória do mandante, empate e vitória do visitante para cada situação de expulsão - Plotly Express

resultado                     Empate  Vitória mandante  Vitória visitante
situacao_vermelhos
Expulsão apenas do mandante    30.08             24.81              45.11
Expulsão apenas do visitante   25.88             61.65              12.47
Expulsões iguais               39.24             34.18              26.58
Mais expulsões do mandante     28.57             28.57              42.86
Mais expulsões do visitante    20.00             30.00              50.00
Nenhuma expulsão               26.46             49.04              24.50

In [126]:
disciplina_casa = df_analise[
    [
        "mandante",
        "faltas_mandante",
        "cartao_amarelo_mandante",
        "cartao_vermelho_mandante"
    ]
].copy()

disciplina_casa.columns = [
    "time",
    "faltas",
    "amarelos",
    "vermelhos"
]


disciplina_fora = df_analise[
    [
        "visitante",
        "faltas_visitante",
        "cartao_amarelo_visitante",
        "cartao_vermelho_visitante"
    ]
].copy()

disciplina_fora.columns = [
    "time",
    "faltas",
    "amarelos",
    "vermelhos"
]


dados_disciplina = pd.concat(
    [disciplina_casa, disciplina_fora],
    ignore_index=True
)

dados_disciplina.head()

          time  faltas  amarelos  vermelhos
0  Chapecoense      20         2          0
1    Palmeiras      20         2          0
2   Fluminense       9         2          0
3       Gremio      17         3          0
4     Cruzeiro      17         3          0

In [128]:
disciplina_times = (
    dados_disciplina
    .groupby("time")
    .agg(
        jogos=("time", "count"),
        faltas=("faltas", "sum"),
        amarelos=("amarelos", "sum"),
        vermelhos=("vermelhos", "sum")
    )
)

disciplina_times.head()

              jogos  faltas  amarelos  vermelhos
time
America-MG      190    2810       380         28
Athletico-PR    342    4849       724         31
Atletico-GO     152    2297       351         18
Atletico-MG     379    5436       827         38
Avai            152    2222       375         22

In [129]:
top_faltas = (
    disciplina_times
    .sort_values("faltas", ascending=False)
    [["jogos", "faltas", "amarelos", "vermelhos"]]
    .head(10)
)

print("TOP 10 - CLUBES COM MAIS FALTAS")
print(top_faltas)

TOP 10 - CLUBES COM MAIS FALTAS
               jogos  faltas  amarelos  vermelhos
time
Palmeiras        380    5892       859         42
Sao Paulo        380    5719       884         45
Flamengo         380    5478       800         46
Atletico-MG      379    5436       827         38
Santos           380    5412       896         52
Fluminense       380    5331       874         56
Internacional    342    5211       859         56
Corinthians      380    4953       778         34
Athletico-PR     342    4849       724         31
Gremio           342    4717       782         37

In [130]:
disciplina_times["media_faltas"] = (
    disciplina_times["faltas"] /
    disciplina_times["jogos"]
)

In [131]:
disciplina_times["media_amarelos"] = (
    disciplina_times["amarelos"] /
    disciplina_times["jogos"]
)

In [132]:
disciplina_times["media_vermelhos"] = (
    disciplina_times["vermelhos"] /
    disciplina_times["jogos"]
)

In [133]:
disciplina_times[
    ["media_faltas", "media_amarelos", "media_vermelhos"]
] = disciplina_times[
    ["media_faltas", "media_amarelos", "media_vermelhos"]
].round(2)

In [ ]:
disciplina_times.sort_values(
    "media_faltas",
    ascending=False
).head(10)

# Gráfico sugerido: gráfico de barras horizontais dos clubes com maior média de faltas por partida - Plotly Express

,jogos,faltas,amarelos,vermelhos,media_faltas,media_amarelos,media_vermelhos
time,,,,,,,
Figueirense,76,1333,197,13,17.54,2.59,0.17
Ponte Preta,114,1915,284,17,16.80,2.49,0.15
Vitoria,152,2542,411,27,16.72,2.70,0.18
Joinville,38,630,94,8,16.58,2.47,0.21
Chapecoense,227,3616,486,20,15.93,2.14,0.09
Coritiba,228,3588,614,38,15.74,2.69,0.17
Parana,38,597,98,9,15.71,2.58,0.24
Palmeiras,380,5892,859,42,15.51,2.26,0.11
Santa Cruz,38,581,84,6,15.29,2.21,0.16
Internacional,342,5211,859,56,15.24,2.51,0.16

In [135]:
disciplina_times["amarelos_por_100_faltas"] = (
    disciplina_times["amarelos"] /
    disciplina_times["faltas"] * 100
)

In [136]:
disciplina_times["vermelhos_por_100_faltas"] = (
    disciplina_times["vermelhos"] /
    disciplina_times["faltas"] * 100
)

In [137]:
disciplina_times[
    ["amarelos_por_100_faltas", "vermelhos_por_100_faltas"]
] = disciplina_times[
    ["amarelos_por_100_faltas", "vermelhos_por_100_faltas"]
].round(2)

In [ ]:
disciplina_times.sort_values(
    "amarelos_por_100_faltas",
    ascending=False
)[
    ["jogos", "faltas", "amarelos", "amarelos_por_100_faltas", "vermelhos_por_100_faltas"]
].head(10)

# Gráfico sugerido: gráfico de barras horizontais dos clubes com maior número de cartões amarelos por 100 faltas - Plotly Express

,jogos,faltas,amarelos,amarelos_por_100_faltas,vermelhos_por_100_faltas
time,,,,,
Mirassol,38,431,86,19.95,0.23
Juventude,114,1678,302,18.00,0.95
Cruzeiro,266,3740,647,17.30,0.94
Coritiba,228,3588,614,17.11,1.06
Vasco,266,3910,665,17.01,1.20
Avai,152,2222,375,16.88,0.99
Goias,190,2893,488,16.87,0.86
Gremio,342,4717,782,16.58,0.78
Santos,380,5412,896,16.56,0.96
Ceara,228,3339,552,16.53,0.81

In [ ]:
corr_faltas_amarelos = dados_disciplina["faltas"].corr(
    dados_disciplina["amarelos"]
)

print(
    f"Correlação entre faltas e cartões amarelos: "
    f"{corr_faltas_amarelos:.3f}"
)
# Gráfico sugerido: gráfico de dispersão entre faltas e cartões amarelos por equipe em cada partida, com linha de tendência - Plotly Express

Correlação entre faltas e cartões amarelos: 0.336

In [ ]:
corr_faltas_vermelhos = dados_disciplina["faltas"].corr(
    dados_disciplina["vermelhos"]
)

print(
    f"Correlação entre faltas e cartões vermelhos: "
    f"{corr_faltas_vermelhos:.3f}"
)

# Gráfico sugerido: gráfico de dispersão entre faltas e cartões vermelhos por equipe em cada partida - Plotly Express

Correlação entre faltas e cartões vermelhos: 0.007

In [142]:
print(gols["minuto"].head(20))
print(gols["minuto"].dtype)

0     31
1     45
2     59
3      6
4     90
5     80
6     63
7     13
8     22
9     56
10    16
11    80
12    73
13    83
14    88
15    12
16    45
17    36
18    78
19    83
Name: minuto, dtype: str
str

In [144]:
gols[gols["minuto"].str.contains(r"\+", na=False)]["minuto"].head(20)

22     90+2
59     45+1
79     90+2
88     90+1
91     45+1
97     90+1
107    90+2
154    90+4
163    90+2
180    45+1
187    90+3
189    45+2
209    90+1
214    90+2
223    45+3
250    90+1
256    90+4
280    90+3
286    45+1
287    90+3
Name: minuto, dtype: str

In [145]:
def converter_minuto(valor):
    valor = str(valor)

    if "+" in valor:
        minuto, acrescimo = valor.split("+")
        return int(minuto) + int(acrescimo)

    return int(valor)


gols_analise = gols.copy()

gols_analise["minuto_num"] = gols_analise["minuto"].apply(
    converter_minuto
)

In [146]:
gols_analise[
    ["minuto", "minuto_num"]
].head(30)

   minuto  minuto_num
0      31          31
1      45          45
2      59          59
3       6           6
4      90          90
5      80          80
6      63          63
7      13          13
8      22          22
9      56          56
10     16          16
11     80          80
12     73          73
13     83          83
14     88          88
15     12          12
16     45          45
17     36          36
18     78          78
19     83          83
20     11          11
21     50          50
22   90+2          92
23     75          75
24      9           9
25     35          35
26     64          64
27     80          80
28      9           9
29     12          12

In [152]:
def classificar_faixa_minuto(valor):
    valor = str(valor)
    minuto_base = int(valor.split("+")[0])

    if minuto_base <= 15:
        return "0–15"
    elif minuto_base <= 30:
        return "16–30"
    elif minuto_base <= 45:
        return "31–45+"
    elif minuto_base <= 60:
        return "46–60"
    elif minuto_base <= 75:
        return "61–75"
    else:
        return "76–90+"


gols_analise["faixa_minuto"] = gols_analise["minuto"].apply(
    classificar_faixa_minuto
)

In [148]:
gols_analise["tempo"] = gols_analise["minuto"].apply(
    lambda x: "1º tempo"
    if int(str(x).split("+")[0]) <= 45
    else "2º tempo"
)

In [153]:
print(
    gols_analise["faixa_minuto"]
    .value_counts()
    .reindex([
        "0–15",
        "16–30",
        "31–45+",
        "46–60",
        "61–75",
        "76–90+"
    ])
)

faixa_minuto
0–15      1327
16–30     1458
31–45+    2011
46–60     1703
61–75     1774
76–90+    2547
Name: count, dtype: int64

In [ ]:
print(
    (
        gols_analise["faixa_minuto"]
        .value_counts(normalize=True)
        .reindex([
            "0–15",
            "16–30",
            "31–45+",
            "46–60",
            "61–75",
            "76–90+"
        ]) * 100
    ).round(2)
)
# Gráfico sugerido: gráfico de barras com a porcentagem de gols por faixa de 15 minutos, mantendo os acréscimos junto ao respectivo tempo - Plotly Express

faixa_minuto
0–15      12.26
16–30     13.48
31–45+    18.59
46–60     15.74
61–75     16.40
76–90+    23.54
Name: proportion, dtype: float64

In [ ]:
print(gols_analise["tempo"].value_counts())

print(
    (gols_analise["tempo"].value_counts(normalize=True) * 100)
    .round(2)
)
# Gráfico sugerido: gráfico de barras comparando a porcentagem de gols no 1º e no 2º tempo - Plotly Express

tempo
2º tempo    6024
1º tempo    4796
Name: count, dtype: int64
tempo
2º tempo    55.67
1º tempo    44.33
Name: proportion, dtype: float64

In [156]:
desempenho_casa = df_analise[
    ["mandante", "gols_mandante", "gols_visitante"]
].copy()

desempenho_casa.columns = [
    "time",
    "gols_feitos",
    "gols_sofridos"
]


desempenho_fora = df_analise[
    ["visitante", "gols_visitante", "gols_mandante"]
].copy()

desempenho_fora.columns = [
    "time",
    "gols_feitos",
    "gols_sofridos"
]


dados_desempenho = pd.concat(
    [desempenho_casa, desempenho_fora],
    ignore_index=True
)

In [157]:
desempenho_times = (
    dados_desempenho
    .groupby("time")
    .agg(
        jogos=("time", "count"),
        gols_feitos=("gols_feitos", "sum"),
        gols_sofridos=("gols_sofridos", "sum")
    )
)

In [158]:
desempenho_times["media_gols_feitos"] = (
    desempenho_times["gols_feitos"] /
    desempenho_times["jogos"]
)

desempenho_times["media_gols_sofridos"] = (
    desempenho_times["gols_sofridos"] /
    desempenho_times["jogos"]
)

desempenho_times["saldo_medio"] = (
    desempenho_times["media_gols_feitos"] -
    desempenho_times["media_gols_sofridos"]
)

desempenho_times[
    ["media_gols_feitos", "media_gols_sofridos", "saldo_medio"]
] = desempenho_times[
    ["media_gols_feitos", "media_gols_sofridos", "saldo_medio"]
].round(2)

In [ ]:
top_ataques = (
    desempenho_times
    .sort_values("media_gols_feitos", ascending=False)
    [["jogos", "gols_feitos", "media_gols_feitos"]]
    .head(10)
)

print("TOP 10 - MAIOR MÉDIA DE GOLS MARCADOS")
print(top_ataques)
# Gráfico sugerido: gráfico de barras horizontais com os clubes de maior média de gols marcados por partida - Plotly Express

TOP 10 - MAIOR MÉDIA DE GOLS MARCADOS
               jogos  gols_feitos  media_gols_feitos
time
Mirassol          38           63               1.66
Flamengo         380          622               1.64
Palmeiras        380          613               1.61
Atletico-MG      379          550               1.45
Gremio           342          467               1.37
Bragantino       190          248               1.31
Santos           380          481               1.27
Internacional    342          422               1.23
Fluminense       380          462               1.22
Corinthians      380          463               1.22

In [ ]:
top_defesas = (
    desempenho_times
    .sort_values("media_gols_sofridos", ascending=True)
    [["jogos", "gols_sofridos", "media_gols_sofridos"]]
    .head(10)
)

print("TOP 10 - MENOR MÉDIA DE GOLS SOFRIDOS")
print(top_defesas)
# Gráfico sugerido: gráfico de barras horizontais com os clubes de menor média de gols sofridos por partida - Plotly Express

TOP 10 - MENOR MÉDIA DE GOLS SOFRIDOS
               jogos  gols_sofridos  media_gols_sofridos
time
Palmeiras        380            359                 0.94
Cruzeiro         266            266                 1.00
Flamengo         380            384                 1.01
Corinthians      380            384                 1.01
Mirassol          38             39                 1.03
Internacional    342            357                 1.04
Cuiaba           114            118                 1.04
Athletico-PR     342            364                 1.06
Sao Paulo        380            403                 1.06
Ceara            228            249                 1.09

In [ ]:
top_saldo = (
    desempenho_times
    .sort_values("saldo_medio", ascending=False)
    [[
        "jogos",
        "media_gols_feitos",
        "media_gols_sofridos",
        "saldo_medio"
    ]]
    .head(10)
)

print("TOP 10 - MELHOR SALDO MÉDIO DE GOLS")
print(top_saldo)
# Gráfico sugerido: gráfico de barras horizontais dos clubes com maior saldo médio de gols por partida - Plotly Express

TOP 10 - MELHOR SALDO MÉDIO DE GOLS
               jogos  media_gols_feitos  media_gols_sofridos  saldo_medio
time
Palmeiras        380               1.61                 0.94         0.67
Flamengo         380               1.64                 1.01         0.63
Mirassol          38               1.66                 1.03         0.63
Atletico-MG      379               1.45                 1.13         0.32
Gremio           342               1.37                 1.10         0.27
Corinthians      380               1.22                 1.01         0.21
Internacional    342               1.23                 1.04         0.19
Sao Paulo        380               1.21                 1.06         0.14
Santos           380               1.27                 1.12         0.14
Athletico-PR     342               1.20                 1.06         0.13

In [162]:
top_media_amarelos = (
    disciplina_times
    .sort_values("media_amarelos", ascending=False)
    [["jogos", "amarelos", "media_amarelos"]]
    .head(10)
)

print("TOP 10 - MAIOR MÉDIA DE CARTÕES AMARELOS POR PARTIDA")
print(top_media_amarelos)

TOP 10 - MAIOR MÉDIA DE CARTÕES AMARELOS POR PARTIDA
               jogos  amarelos  media_amarelos
time
Vitoria          152       411            2.70
Coritiba         228       614            2.69
Juventude        114       302            2.65
Figueirense       76       197            2.59
Parana            38        98            2.58
Goias            190       488            2.57
Internacional    342       859            2.51
Vasco            266       665            2.50
Ponte Preta      114       284            2.49
Joinville         38        94            2.47

In [ ]:
top_amarelos = (
    disciplina_times
    .sort_values("amarelos", ascending=False)
    [["jogos", "amarelos", "media_amarelos"]]
    .head(10)
)

print("TOP 10 - MAIOR NÚMERO DE CARTÕES AMARELOS")
print(top_amarelos)
# Gráfico sugerido: gráfico de barras horizontais com os clubes de maior média de cartões amarelos por partida - Plotly Express

# Gráfico sugerido: gráfico de barras horizontais com os clubes que receberam mais cartões amarelos no período - Plotly Express

TOP 10 - MAIOR NÚMERO DE CARTÕES AMARELOS
               jogos  amarelos  media_amarelos
time
Santos           380       896            2.36
Sao Paulo        380       884            2.33
Fluminense       380       874            2.30
Internacional    342       859            2.51
Palmeiras        380       859            2.26
Atletico-MG      379       827            2.18
Flamengo         380       800            2.11
Gremio           342       782            2.29
Corinthians      380       778            2.05
Athletico-PR     342       724            2.12

In [164]:
df_analise["faltas_total"] = (
    df_analise["faltas_mandante"] +
    df_analise["faltas_visitante"]
)

df_analise["escanteios_total"] = (
    df_analise["escanteios_mandante"] +
    df_analise["escanteios_visitante"]
)

In [165]:
def contar_outliers(serie):
    q1 = serie.quantile(0.25)
    q3 = serie.quantile(0.75)

    iqr = q3 - q1

    limite_inferior = q1 - 1.5 * iqr
    limite_superior = q3 + 1.5 * iqr

    outliers = serie[
        (serie < limite_inferior) |
        (serie > limite_superior)
    ]

    return {
        "Q1": q1,
        "Q3": q3,
        "Limite inferior": limite_inferior,
        "Limite superior": limite_superior,
        "Quantidade de outliers": len(outliers)
    }

In [ ]:
for coluna in [
    "gols_total",
    "chutes_total",
    "faltas_total",
    "escanteios_total"
]:
    print(f"\n{coluna}")
    print(contar_outliers(df_analise[coluna]))
    # Gráfico sugerido: boxplots para gols totais, chutes totais, faltas totais e escanteios totais, destacando valores extremos - Plotly Express

gols_total
{'Q1': np.float64(1.0), 'Q3': np.float64(3.0), 'Limite inferior': np.float64(-2.0), 'Limite superior': np.float64(6.0), 'Quantidade de outliers': 51}

chutes_total
{'Q1': np.float64(21.0), 'Q3': np.float64(29.0), 'Limite inferior': np.float64(9.0), 'Limite superior': np.float64(41.0), 'Quantidade de outliers': 40}

faltas_total
{'Q1': np.float64(25.0), 'Q3': np.float64(34.0), 'Limite inferior': np.float64(11.5), 'Limite superior': np.float64(47.5), 'Quantidade de outliers': 58}

escanteios_total
{'Q1': np.float64(8.0), 'Q3': np.float64(13.0), 'Limite inferior': np.float64(0.5), 'Limite superior': np.float64(20.5), 'Quantidade de outliers': 46}