In [1]:
import pandas as pd

In [2]:
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [3]:
cartoes = pd.read_csv('campeonato-brasileiro-cartoes.csv')
estatisticas_completas = pd.read_csv("campeonato-brasileiro-estatisticas-full.csv")
jogos = pd.read_csv("campeonato-brasileiro-full.csv")
gols = pd.read_csv("campeonato-brasileiro-gols.csv")

In [4]:
cartoes.head()

,partida_id,rodata,clube,cartao,atleta,num_camisa,posicao,minuto
0,4607,1,Figueirense,Amarelo,Thiago Heleno,4.0,Zagueiro,44
1,4607,1,Figueirense,Amarelo,Paulo Roberto da Silva,28.0,NaN,66
2,4608,1,Internacional,Amarelo,Juan Silveira dos Santos,4.0,Zagueiro,20
3,4608,1,Vitoria,Amarelo,Vinícius Santos Silva,NaN,NaN,82
4,4608,1,Internacional,Amarelo,Andrés D'Alessandro,10.0,Meio-campo,72

In [5]:
estatisticas_completas.head()

,partida_id,rodata,clube,chutes,chutes_no_alvo,posse_de_bola,passes,precisao_passes,faltas,cartao_amarelo,cartao_vermelho,impedimentos,escanteios
0,1,1,Vasco,0,0,NaN,0,NaN,0,0,0,0,0
1,1,1,Guarani,0,0,NaN,0,NaN,0,0,0,0,0
2,2,1,Athletico-PR,0,0,NaN,0,NaN,0,0,0,0,0
3,2,1,Gremio,0,0,NaN,0,NaN,0,0,0,0,0
4,3,1,Flamengo,0,0,NaN,0,NaN,0,0,0,0,0

In [6]:
jogos.head()

,ID,rodata,data,hora,mandante,visitante,formacao_mandante,formacao_visitante,tecnico_mandante,tecnico_visitante,vencedor,arena,mandante_Placar,visitante_Placar,mandante_Estado,visitante_Estado,arrecadacao
0,1,1,29/03/2003,16:00,Guarani,Vasco,NaN,NaN,NaN,NaN,Guarani,Brinco de Ouro,4,2,SP,RJ,NaN
1,2,1,29/03/2003,16:00,Athletico-PR,Gremio,NaN,NaN,NaN,NaN,Athletico-PR,Arena da Baixada,2,0,PR,RS,NaN
2,3,1,30/03/2003,16:00,Flamengo,Coritiba,NaN,NaN,NaN,NaN,-,Maracanã,1,1,RJ,PR,NaN
3,4,1,30/03/2003,16:00,Goias,Paysandu,NaN,NaN,NaN,NaN,-,Serra Dourada,2,2,GO,PA,NaN
4,5,1,30/03/2003,16:00,Internacional,Ponte Preta,NaN,NaN,NaN,NaN,-,Beira Rio,1,1,RS,SP,NaN

In [7]:
gols.head()

,partida_id,rodata,clube,atleta,minuto,tipo_de_gol
0,4607,1,Fluminense,Rafael Sóbis,31,NaN
1,4607,1,Fluminense,Fred,45,Penalty
2,4607,1,Fluminense,Nirley da Silva Fonseca,59,Gol Contra
3,4608,1,Internacional,Charles Aránguiz,6,NaN
4,4612,1,Cruzeiro,Marcelo Moreno,90,NaN

In [8]:
print(jogos.shape)
print(estatisticas_completas.shape)
print(gols.shape)
print(cartoes.shape)

(9165, 17)
(18330, 13)
(10820, 6)
(20953, 8)

In [9]:
print(f'{jogos.isna().sum()}\n')
print(f'{estatisticas_completas.isna().sum()}\n')
print(f'{gols.isna().sum()}\n')
print(f'{cartoes.isna().sum()}')

ID                       0
rodata                   0
data                     0
hora                     0
mandante                 0
visitante                0
formacao_mandante     4975
formacao_visitante    4975
tecnico_mandante      4610
tecnico_visitante     4610
vencedor                 0
arena                    0
mandante_Placar          0
visitante_Placar         0
mandante_Estado          0
visitante_Estado         0
arrecadacao           8785
dtype: int64

partida_id             0
rodata                 0
clube                  0
chutes                 0
chutes_no_alvo         0
posse_de_bola      10762
passes                 0
precisao_passes    13066
faltas                 0
cartao_amarelo         0
cartao_vermelho        0
impedimentos           0
escanteios             0
dtype: int64

partida_id        0
rodata            0
clube             0
atleta            0
minuto            0
tipo_de_gol    9527
dtype: int64

partida_id       0
rodata           0
clube            0
cartao           0
atleta           6
num_camisa     386
posicao       1198
minuto           0
dtype: int64

In [10]:
print(jogos["rodata"].value_counts().sort_index())

rodata
1     235
2     235
3     235
4     235
5     235
6     235
7     235
8     235
9     235
10    235
11    235
12    235
13    235
14    234
15    236
16    235
17    235
18    235
19    235
20    235
21    235
22    235
23    235
24    235
25    235
26    235
27    235
28    235
29    235
30    235
31    235
32    235
33    235
34    235
35    235
36    235
37    235
38    234
39     35
40     35
41     35
42     35
43     24
44     24
45     24
46     24
Name: count, dtype: int64

In [11]:
jogos["data"] = pd.to_datetime(jogos["data"], dayfirst=True)

jogos["temporada"] = jogos["data"].dt.year

In [12]:
stats_ano = estatisticas_completas.merge(
    jogos[["ID", "temporada"]],
    left_on="partida_id",
    right_on="ID",
    how="left"
)

In [13]:
nulos_por_ano =stats_ano.groupby("temporada")[["posse_de_bola", "precisao_passes"]].apply(lambda x: x.isna().sum())

print(nulos_por_ano)

           posse_de_bola  precisao_passes
temporada
2003                1104             1104
2004                1104             1104
2005                 924              924
2006                 760              760
2007                 760              760
2008                 760              760
2009                 760              760
2010                 760              760
2011                 760              760
2012                 760              760
2013                 760              760
2014                 728              760
2015                   0              760
2016                   0              758
2017                   2              760
2018                   0                0
2019                  46               46
2020                   2                2
2021                   0                0
2022                   0                0
2023                   0                0
2024                 760              760
2025                  12                8

In [14]:
jogos_analise = jogos.copy()
stats_analise = estatisticas_completas.copy()

In [15]:
jogos_analise["data"] = pd.to_datetime(jogos_analise["data"], dayfirst=True)

In [16]:
jogos_analise["temporada"] = jogos_analise["data"].dt.year

In [17]:
temporadas = list(range(2015, 2024)) + [2025]

In [18]:
jogos_analise = jogos_analise[jogos_analise["temporada"].isin(temporadas)].copy()

In [19]:
jogos_analise.shape

(3799, 18)

In [20]:
jogos_analise['temporada'].value_counts().sort_index()

temporada
2015    380
2016    379
2017    380
2018    380
2019    380
2020    268
2021    492
2022    380
2023    380
2025    380
Name: count, dtype: int64

In [21]:
jogos_analise["temporada"] = jogos_analise["data"].dt.year

In [22]:
jogos_analise.loc[(jogos_analise["data"] <= "2021-02-28") &(jogos_analise["data"] >= "2021-01-01"),"temporada"] = 2020

In [23]:
temporadas = list(range(2015, 2024)) + [2025]

In [24]:
jogos_analise = jogos_analise[jogos_analise["temporada"].isin(temporadas)].copy()

In [25]:
jogos_analise.shape

(3799, 18)

In [26]:
jogos_analise['temporada'].value_counts().sort_index()

temporada
2015    380
2016    379
2017    380
2018    380
2019    380
2020    380
2021    380
2022    380
2023    380
2025    380
Name: count, dtype: int64

In [27]:
colunas_stats = [
    "partida_id",
    "clube",
    "chutes",
    "chutes_no_alvo",
    "posse_de_bola",
    "passes",
    "faltas",
    "cartao_amarelo",
    "cartao_vermelho",
    "impedimentos",
    "escanteios"
]

In [28]:
stats_analise = stats_analise[colunas_stats].copy()

In [29]:
stats_analise.head()

,partida_id,clube,chutes,chutes_no_alvo,posse_de_bola,passes,faltas,cartao_amarelo,cartao_vermelho,impedimentos,escanteios
0,1,Vasco,0,0,NaN,0,0,0,0,0,0
1,1,Guarani,0,0,NaN,0,0,0,0,0,0
2,2,Athletico-PR,0,0,NaN,0,0,0,0,0,0
3,2,Gremio,0,0,NaN,0,0,0,0,0,0
4,3,Flamengo,0,0,NaN,0,0,0,0,0,0

In [30]:
stats_analise.shape

(18330, 11)

In [31]:
ids_partidas = jogos_analise["ID"]

In [32]:
stats_analise = stats_analise[stats_analise["partida_id"].isin(ids_partidas)].copy()

In [33]:
stats_analise.shape

(7598, 11)

In [34]:
stats_mandante = stats_analise.merge(jogos_analise[["ID", "mandante"]],left_on=["partida_id", "clube"],right_on=["ID", "mandante"],how="inner")

In [35]:
stats_mandante.shape

(3799, 13)

In [36]:
stats_mandante.head()

,partida_id,clube,chutes,chutes_no_alvo,posse_de_bola,passes,faltas,cartao_amarelo,cartao_vermelho,impedimentos,escanteios,ID,mandante
0,4987,Chapecoense,13,0,45%,326,20,2,0,3,3,4987,Chapecoense
1,4988,Palmeiras,17,0,50%,406,20,2,0,2,11,4988,Palmeiras
2,4989,Fluminense,26,11,74%,702,9,2,0,1,5,4989,Fluminense
3,4990,Gremio,11,0,45%,401,17,3,0,2,5,4990,Gremio
4,4993,Cruzeiro,13,0,56%,487,17,3,0,4,2,4993,Cruzeiro

In [37]:
stats_visitante = stats_analise.merge(jogos_analise[["ID", "visitante"]],left_on=["partida_id", "clube"],right_on=["ID", "visitante"],how="inner")

In [38]:
stats_visitante.shape

(3799, 13)

In [39]:
stats_visitante.head()

,partida_id,clube,chutes,chutes_no_alvo,posse_de_bola,passes,faltas,cartao_amarelo,cartao_vermelho,impedimentos,escanteios,ID,visitante
0,4987,Coritiba,16,0,55%,388,21,2,0,0,5,4987,Coritiba
1,4988,Atletico-MG,10,0,50%,426,14,4,0,4,2,4988,Atletico-MG
2,4989,Joinville,3,0,26%,250,14,0,1,1,3,4989,Joinville
3,4990,Ponte Preta,17,0,55%,473,21,4,1,0,10,4990,Ponte Preta
4,4993,Corinthians,11,0,44%,391,15,1,0,2,4,4993,Corinthians

In [40]:
stats_mandante = stats_mandante.rename(
    columns={
        "chutes": "chutes_mandante",
        "chutes_no_alvo": "chutes_no_alvo_mandante",
        "posse_de_bola": "posse_mandante",
        "passes": "passes_mandante",
        "faltas": "faltas_mandante",
        "cartao_amarelo": "cartao_amarelo_mandante",
        "cartao_vermelho": "cartao_vermelho_mandante",
        "impedimentos": "impedimentos_mandante",
        "escanteios": "escanteios_mandante"
    }
)

In [41]:
stats_mandante.columns.tolist()

['partida_id',
 'clube',
 'chutes_mandante',
 'chutes_no_alvo_mandante',
 'posse_mandante',
 'passes_mandante',
 'faltas_mandante',
 'cartao_amarelo_mandante',
 'cartao_vermelho_mandante',
 'impedimentos_mandante',
 'escanteios_mandante',
 'ID',
 'mandante']

In [42]:
stats_visitante = stats_visitante.rename(
    columns={
        "chutes": "chutes_visitante",
        "chutes_no_alvo": "chutes_no_alvo_visitante",
        "posse_de_bola": "posse_visitante",
        "passes": "passes_visitante",
        "faltas": "faltas_visitante",
        "cartao_amarelo": "cartao_amarelo_visitante",
        "cartao_vermelho": "cartao_vermelho_visitante",
        "impedimentos": "impedimentos_visitante",
        "escanteios": "escanteios_visitante"
    }
)

In [43]:
stats_visitante.columns.tolist()

['partida_id',
 'clube',
 'chutes_visitante',
 'chutes_no_alvo_visitante',
 'posse_visitante',
 'passes_visitante',
 'faltas_visitante',
 'cartao_amarelo_visitante',
 'cartao_vermelho_visitante',
 'impedimentos_visitante',
 'escanteios_visitante',
 'ID',
 'visitante']

In [44]:
df_analise = jogos_analise[["ID","temporada","rodata","data","hora","mandante","visitante","mandante_Placar","visitante_Placar"]].copy()

In [45]:
df_analise = df_analise.rename(columns={"ID": "partida_id","mandante_Placar": "gols_mandante","visitante_Placar": "gols_visitante", "rodata": "rodada" })

In [46]:
df_analise.shape

(3799, 9)

In [47]:
df_analise.head()

,partida_id,temporada,rodada,data,hora,mandante,visitante,gols_mandante,gols_visitante
4986,4987,2015,1,2015-05-09,18:32,Chapecoense,Coritiba,2,1
4987,4988,2015,1,2015-05-09,18:33,Palmeiras,Atletico-MG,2,2
4988,4989,2015,1,2015-05-09,21:00,Fluminense,Joinville,1,0
4989,4990,2015,1,2015-05-10,11:00,Gremio,Ponte Preta,3,3
4990,4993,2015,1,2015-05-10,15:59,Cruzeiro,Corinthians,0,1

In [48]:
df_analise = df_analise.merge(stats_mandante[[
            "partida_id",
            "chutes_mandante",
            "chutes_no_alvo_mandante",
            "posse_mandante",
            "passes_mandante",
            "faltas_mandante",
            "cartao_amarelo_mandante",
            "cartao_vermelho_mandante",
            "impedimentos_mandante",
            "escanteios_mandante"
        ]],on="partida_id",how="left")

In [49]:
df_analise.shape

(3799, 18)

In [50]:
df_analise.head()

,partida_id,temporada,rodada,data,hora,mandante,visitante,gols_mandante,gols_visitante,chutes_mandante,chutes_no_alvo_mandante,posse_mandante,passes_mandante,faltas_mandante,cartao_amarelo_mandante,cartao_vermelho_mandante,impedimentos_mandante,escanteios_mandante
0,4987,2015,1,2015-05-09,18:32,Chapecoense,Coritiba,2,1,13,0,45%,326,20,2,0,3,3
1,4988,2015,1,2015-05-09,18:33,Palmeiras,Atletico-MG,2,2,17,0,50%,406,20,2,0,2,11
2,4989,2015,1,2015-05-09,21:00,Fluminense,Joinville,1,0,26,11,74%,702,9,2,0,1,5
3,4990,2015,1,2015-05-10,11:00,Gremio,Ponte Preta,3,3,11,0,45%,401,17,3,0,2,5
4,4993,2015,1,2015-05-10,15:59,Cruzeiro,Corinthians,0,1,13,0,56%,487,17,3,0,4,2

In [51]:
df_analise = df_analise.merge(stats_visitante[[
            "partida_id",
            "chutes_visitante",
            "chutes_no_alvo_visitante",
            "posse_visitante",
            "passes_visitante",
            "faltas_visitante",
            "cartao_amarelo_visitante",
            "cartao_vermelho_visitante",
            "impedimentos_visitante",
            "escanteios_visitante"
        ]],on="partida_id",how="left")

In [52]:
df_analise.shape

(3799, 27)

In [53]:
df_analise.columns.tolist()

['partida_id',
 'temporada',
 'rodada',
 'data',
 'hora',
 'mandante',
 'visitante',
 'gols_mandante',
 'gols_visitante',
 'chutes_mandante',
 'chutes_no_alvo_mandante',
 'posse_mandante',
 'passes_mandante',
 'faltas_mandante',
 'cartao_amarelo_mandante',
 'cartao_vermelho_mandante',
 'impedimentos_mandante',
 'escanteios_mandante',
 'chutes_visitante',
 'chutes_no_alvo_visitante',
 'posse_visitante',
 'passes_visitante',
 'faltas_visitante',
 'cartao_amarelo_visitante',
 'cartao_vermelho_visitante',
 'impedimentos_visitante',
 'escanteios_visitante']

In [54]:
df_analise.isna().sum()

partida_id                    0
temporada                     0
rodada                        0
data                          0
hora                          0
mandante                      0
visitante                     0
gols_mandante                 0
gols_visitante                0
chutes_mandante               0
chutes_no_alvo_mandante       0
posse_mandante               31
passes_mandante               0
faltas_mandante               0
cartao_amarelo_mandante       0
cartao_vermelho_mandante      0
impedimentos_mandante         0
escanteios_mandante           0
chutes_visitante              0
chutes_no_alvo_visitante      0
posse_visitante              31
passes_visitante              0
faltas_visitante              0
cartao_amarelo_visitante      0
cartao_vermelho_visitante     0
impedimentos_visitante        0
escanteios_visitante          0
dtype: int64

In [55]:
df_analise["partida_id"].duplicated().sum()

np.int64(0)

In [56]:
df_analise.head()

,partida_id,temporada,rodada,data,hora,mandante,visitante,gols_mandante,gols_visitante,chutes_mandante,...,escanteios_mandante,chutes_visitante,chutes_no_alvo_visitante,posse_visitante,passes_visitante,faltas_visitante,cartao_amarelo_visitante,cartao_vermelho_visitante,impedimentos_visitante,escanteios_visitante
0,4987,2015,1,2015-05-09,18:32,Chapecoense,Coritiba,2,1,13,...,3,16,0,55%,388,21,2,0,0,5
1,4988,2015,1,2015-05-09,18:33,Palmeiras,Atletico-MG,2,2,17,...,11,10,0,50%,426,14,4,0,4,2
2,4989,2015,1,2015-05-09,21:00,Fluminense,Joinville,1,0,26,...,5,3,0,26%,250,14,0,1,1,3
3,4990,2015,1,2015-05-10,11:00,Gremio,Ponte Preta,3,3,11,...,5,17,0,55%,473,21,4,1,0,10
4,4993,2015,1,2015-05-10,15:59,Cruzeiro,Corinthians,0,1,13,...,2,11,0,44%,391,15,1,0,2,4

In [57]:
df_analise.info()

<class 'pandas.DataFrame'>
RangeIndex: 3799 entries, 0 to 3798
Data columns (total 27 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   partida_id                 3799 non-null   int64
 1   temporada                  3799 non-null   int32
 2   rodada                     3799 non-null   int64
 3   data                       3799 non-null   datetime64[us]
 4   hora                       3799 non-null   str
 5   mandante                   3799 non-null   str
 6   visitante                  3799 non-null   str
 7   gols_mandante              3799 non-null   int64
 8   gols_visitante             3799 non-null   int64
 9   chutes_mandante            3799 non-null   int64
 10  chutes_no_alvo_mandante    3799 non-null   int64
 11  posse_mandante             3768 non-null   str
 12  passes_mandante            3799 non-null   int64
 13  faltas_mandante            3799 non-null   int64
 14  cartao_amarelo_mandante    3799 non-null   int64
 15  cartao_vermelho_mandante   3799 non-null   int64
 16  impedimentos_mandante      3799 non-null   int64
 17  escanteios_mandante        3799 non-null   int64
 18  chutes_visitante           3799 non-null   int64
 19  chutes_no_alvo_visitante   3799 non-null   int64
 20  posse_visitante            3768 non-null   str
 21  passes_visitante           3799 non-null   int64
 22  faltas_visitante           3799 non-null   int64
 23  cartao_amarelo_visitante   3799 non-null   int64
 24  cartao_vermelho_visitante  3799 non-null   int64
 25  impedimentos_visitante     3799 non-null   int64
 26  escanteios_visitante       3799 non-null   int64
dtypes: datetime64[us](1), int32(1), int64(20), str(5)
memory usage: 893.2 KB

In [58]:
problemas_mandante = df_analise[(df_analise["gols_mandante"] > 0) &(df_analise["chutes_no_alvo_mandante"] == 0)]

In [59]:
len(problemas_mandante)

578

In [60]:
problemas_mandante[["partida_id", "temporada","mandante", "visitante","gols_mandante","chutes_no_alvo_mandante"]]

,partida_id,temporada,mandante,visitante,gols_mandante,chutes_no_alvo_mandante
0,4987,2015,Chapecoense,Coritiba,2,0
1,4988,2015,Palmeiras,Atletico-MG,2,0
3,4990,2015,Gremio,Ponte Preta,3,0
5,4994,2015,Sport,Figueirense,4,0
6,4991,2015,Athletico-PR,Internacional,3,0
...,...,...,...,...,...,...
1842,6841,2019,Athletico-PR,Botafogo-RJ,1,0
1861,6849,2019,Athletico-PR,Gremio,2,0
2017,7015,2020,Atletico-MG,Vasco,4,0
2453,7443,2021,Bragantino,Atletico-MG,1,0
3152,8139,2023,Cruzeiro,Sao Paulo,1,0

In [61]:
problemas_visitante = df_analise[(df_analise["gols_visitante"] > 0) &(df_analise["chutes_no_alvo_visitante"] == 0)]

In [62]:
len(problemas_visitante)

448

In [63]:
problemas_visitante[["partida_id", "temporada","mandante","visitante","gols_visitante","chutes_no_alvo_visitante"]]

,partida_id,temporada,mandante,visitante,gols_visitante,chutes_no_alvo_visitante
0,4987,2015,Chapecoense,Coritiba,1,0
1,4988,2015,Palmeiras,Atletico-MG,2,0
3,4990,2015,Gremio,Ponte Preta,3,0
4,4993,2015,Cruzeiro,Corinthians,1,0
5,4994,2015,Sport,Figueirense,1,0
...,...,...,...,...,...,...
1794,6781,2019,Athletico-PR,Goias,1,0
1831,6820,2019,Sao Paulo,Athletico-PR,1,0
1851,6829,2019,Atletico-MG,Athletico-PR,1,0
2017,7015,2020,Atletico-MG,Vasco,1,0
2088,7081,2020,Bragantino,Santos,1,0

In [64]:
print(problemas_mandante["temporada"].value_counts().sort_index())
print()
print(problemas_visitante["temporada"].value_counts().sort_index())

temporada
2015    275
2016    286
2017      1
2019     13
2020      1
2021      1
2023      1
Name: count, dtype: int64

temporada
2015    207
2016    219
2017      1
2018      2
2019     17
2020      2
Name: count, dtype: int64

In [65]:
df_analise[df_analise["posse_mandante"].isna()]["temporada"].value_counts().sort_index()

temporada
2017     1
2019    23
2020     1
2025     6
Name: count, dtype: int64

In [66]:
df_analise[df_analise["posse_visitante"].isna()]["temporada"].value_counts().sort_index()

temporada
2017     1
2019    23
2020     1
2025     6
Name: count, dtype: int64

In [67]:
df_posse = df_analise.dropna(
    subset=["posse_mandante", "posse_visitante"]
).copy()

print(df_posse.shape)

(3768, 27)

In [68]:
print(df_posse["posse_mandante"].dtype)
print(df_posse["posse_visitante"].dtype)

str
str

In [69]:
df_posse["posse_mandante"] = (
    df_posse["posse_mandante"]
    .str.replace("%", "", regex=False)
    .astype(float)
)

df_posse["posse_visitante"] = (
    df_posse["posse_visitante"]
    .str.replace("%", "", regex=False)
    .astype(float)
)

In [70]:
print("Total de partidas:", len(df_analise))

print("\nGols:")
print("Total de gols:", 
      df_analise["gols_mandante"].sum() + df_analise["gols_visitante"].sum())

print("Média de gols por partida:",
      f"{(df_analise["gols_mandante"] + df_analise["gols_visitante"]).mean():.2f}")

print("\nResultados:")

vitorias_mandante = (
    df_analise["gols_mandante"] > df_analise["gols_visitante"]
).sum()

empates = (
    df_analise["gols_mandante"] == df_analise["gols_visitante"]
).sum()

vitorias_visitante = (
    df_analise["gols_mandante"] < df_analise["gols_visitante"]
).sum()

print("Vitórias do mandante:", vitorias_mandante)
print("Empates:", empates)
print("Vitórias do visitante:", vitorias_visitante)

print("\nPosse de bola:")
print("Média mandante:",
      f"{df_posse["posse_mandante"].mean():.2f}")

print("Média visitante:",
      f"{df_posse["posse_visitante"].mean():.2f}")

Total de partidas: 3799

Gols:
Total de gols: 9031
Média de gols por partida: 2.38

Resultados:
Vitórias do mandante: 1837
Empates: 1022
Vitórias do visitante: 940

Posse de bola:
Média mandante: 51.66
Média visitante: 48.34

In [71]:
df_analise["maior_posse"] = df_analise.apply(
    lambda x: "Mandante" if x["posse_mandante"] > x["posse_visitante"]
    else "Visitante" if x["posse_visitante"] > x["posse_mandante"]
    else "Empate",
    axis=1
)

print(df_analise["maior_posse"].value_counts())

maior_posse
Mandante     2149
Visitante    1603
Empate         47
Name: count, dtype: int64

In [72]:
df_analise["maior_posse"] = df_analise.apply(
    lambda x: "Sem dados" if pd.isna(x["posse_mandante"]) or pd.isna(x["posse_visitante"])
    else "Mandante" if x["posse_mandante"] > x["posse_visitante"]
    else "Visitante" if x["posse_visitante"] > x["posse_mandante"]
    else "Empate",
    axis=1
)

print(df_analise["maior_posse"].value_counts())

maior_posse
Mandante     2149
Visitante    1603
Sem dados      31
Empate         16
Name: count, dtype: int64

In [73]:
df_analise["resultado"] = df_analise.apply(
    lambda x: "Vitória mandante" if x["gols_mandante"] > x["gols_visitante"]
    else "Vitória visitante" if x["gols_visitante"] > x["gols_mandante"]
    else "Empate",
    axis=1
)

print(pd.crosstab(df_analise["maior_posse"], df_analise["resultado"]))

resultado    Empate  Vitória mandante  Vitória visitante
maior_posse
Empate            5                 7                  4
Mandante        611               926                612
Sem dados        11                11                  9
Visitante       395               893                315

In [74]:
tabela_posse = pd.crosstab(
    df_analise["maior_posse"],
    df_analise["resultado"],
    normalize="index"
) * 100

print(tabela_posse.round(2))

resultado    Empate  Vitória mandante  Vitória visitante
maior_posse
Empate        31.25             43.75              25.00
Mandante      28.43             43.09              28.48
Sem dados     35.48             35.48              29.03
Visitante     24.64             55.71              19.65

In [75]:
df_analise["posse_mandante_num"] = (
    df_analise["posse_mandante"]
    .str.replace("%", "", regex=False)
    .astype(float)
)

In [76]:
df_analise["posse_mandante_num"].dtype

dtype('float64')

In [77]:
df_analise["faixa_posse_mandante"] = pd.cut(
    df_analise["posse_mandante_num"],
    bins=[0, 40, 50, 60, 101],
    labels=["Menos de 40%", "40–49%", "50–59%", "60% ou mais"],
    right=False
)

print(df_analise["faixa_posse_mandante"].value_counts().sort_index())

faixa_posse_mandante
Menos de 40%     505
40–49%          1098
50–59%          1237
60% ou mais      928
Name: count, dtype: int64

In [78]:
tabela_faixas = pd.crosstab(
    df_analise["faixa_posse_mandante"],
    df_analise["resultado"],
    normalize="index"
) * 100

print(tabela_faixas.round(2))

resultado             Empate  Vitória mandante  Vitória visitante
faixa_posse_mandante
Menos de 40%           23.76             59.01              17.23
40–49%                 25.05             54.19              20.77
50–59%                 27.00             46.48              26.52
60% ou mais            30.39             38.58              31.03

In [79]:
vitorias_casa = (
    df_analise[df_analise["resultado"] == "Vitória mandante"]
    .groupby("mandante")
    .size()
    .sort_values(ascending=False)
)

print(vitorias_casa.head(10))

mandante
Palmeiras        123
Flamengo         120
Atletico-MG      114
Santos           105
Fluminense       102
Corinthians      101
Gremio           100
Internacional     98
Sao Paulo         98
Athletico-PR      96
dtype: int64

In [80]:
jogos_casa = df_analise.groupby("mandante").size()

taxa_vitoria_casa = (
    (vitorias_casa / jogos_casa) * 100
).sort_values(ascending=False)

print(taxa_vitoria_casa.head(10).round(2))

mandante
Palmeiras        64.74
Flamengo         63.16
Mirassol         63.16
Atletico-MG      60.00
Gremio           58.48
Internacional    57.31
Athletico-PR     56.14
Santos           55.26
Ponte Preta      54.39
Fluminense       53.68
dtype: float64

In [81]:
resumo_casa = pd.DataFrame({
    "jogos_em_casa": jogos_casa,
    "vitorias_em_casa": vitorias_casa
})

resumo_casa["taxa_vitoria"] = (
    resumo_casa["vitorias_em_casa"] /
    resumo_casa["jogos_em_casa"] * 100
)

print(resumo_casa.sort_values("taxa_vitoria", ascending=False).round(2).head(15))

               jogos_em_casa  vitorias_em_casa  taxa_vitoria
mandante
Palmeiras                190               123         64.74
Flamengo                 190               120         63.16
Mirassol                  19                12         63.16
Atletico-MG              190               114         60.00
Gremio                   171               100         58.48
Internacional            171                98         57.31
Athletico-PR             171                96         56.14
Santos                   190               105         55.26
Ponte Preta               57                31         54.39
Fluminense               190               102         53.68
Corinthians              190               101         53.16
Sao Paulo                190                98         51.58
Bahia                    133                66         49.62
Fortaleza                114                54         47.37
Bragantino                95                45         47.37

In [82]:
vitorias_casa = (
    df_analise[df_analise["resultado"] == "Vitória mandante"]
    .groupby("mandante")
    .size()
    .sort_values(ascending=False)
)

print("TOP 10 - VITÓRIAS EM CASA")
print(vitorias_casa.head(10))

TOP 10 - VITÓRIAS EM CASA
mandante
Palmeiras        123
Flamengo         120
Atletico-MG      114
Santos           105
Fluminense       102
Corinthians      101
Gremio           100
Internacional     98
Sao Paulo         98
Athletico-PR      96
dtype: int64

In [83]:
vitorias_fora = (
    df_analise[df_analise["resultado"] == "Vitória visitante"]
    .groupby("visitante")
    .size()
    .sort_values(ascending=False)
)

print("TOP 10 - VITÓRIAS FORA DE CASA")
print(vitorias_fora.head(10))

TOP 10 - VITÓRIAS FORA DE CASA
visitante
Flamengo         81
Palmeiras        80
Atletico-MG      60
Corinthians      54
Sao Paulo        50
Gremio           49
Fluminense       49
Santos           46
Botafogo-RJ      43
Internacional    43
dtype: int64

In [84]:
jogos_casa = df_analise.groupby("mandante").size()

taxa_vitoria_casa = (
    vitorias_casa.reindex(jogos_casa.index, fill_value=0)
    / jogos_casa
    * 100
)

print("TOP 10 - PORCENTAGEM DE VITÓRIAS EM CASA")
print(taxa_vitoria_casa.sort_values(ascending=False).head(10).round(2))

TOP 10 - PORCENTAGEM DE VITÓRIAS EM CASA
mandante
Palmeiras        64.74
Flamengo         63.16
Mirassol         63.16
Atletico-MG      60.00
Gremio           58.48
Internacional    57.31
Athletico-PR     56.14
Santos           55.26
Ponte Preta      54.39
Fluminense       53.68
dtype: float64

In [85]:
jogos_fora = df_analise.groupby("visitante").size()

taxa_vitoria_fora = (
    vitorias_fora.reindex(jogos_fora.index, fill_value=0)
    / jogos_fora
    * 100
)

print("TOP 10 - PORCENTAGEM DE VITÓRIAS FORA")
print(taxa_vitoria_fora.sort_values(ascending=False).head(10).round(2))

TOP 10 - PORCENTAGEM DE VITÓRIAS FORA
visitante
Flamengo       42.63
Palmeiras      42.11
Atletico-MG    31.75
Mirassol       31.58
Gremio         28.65
Corinthians    28.42
Botafogo-RJ    28.29
Cruzeiro       27.07
Sao Paulo      26.32
Cuiaba         26.32
dtype: float64

In [86]:
total_jogos = len(df_analise)

vitorias_mandante = (df_analise["resultado"] == "Vitória mandante").sum()
empates = (df_analise["resultado"] == "Empate").sum()
vitorias_visitante = (df_analise["resultado"] == "Vitória visitante").sum()

print("RESULTADO GERAL")
print(f"Vitória mandante: {vitorias_mandante} ({vitorias_mandante / total_jogos * 100:.2f}%)")
print(f"Empate: {empates} ({empates / total_jogos * 100:.2f}%)")
print(f"Vitória visitante: {vitorias_visitante} ({vitorias_visitante / total_jogos * 100:.2f}%)")

RESULTADO GERAL
Vitória mandante: 1837 (48.35%)
Empate: 1022 (26.90%)
Vitória visitante: 940 (24.74%)

In [87]:
vitorias_casa = (
    df_analise.groupby("mandante")
    .agg(
        jogos_casa=("partida_id", "count"),
        vitorias_casa=("gols_mandante", lambda x: (x > df_analise.loc[x.index, "gols_visitante"]).sum())
    )
)

vitorias_fora = (
    df_analise.groupby("visitante")
    .agg(
        jogos_fora=("partida_id", "count"),
        vitorias_fora=("gols_visitante", lambda x: (x > df_analise.loc[x.index, "gols_mandante"]).sum())
    )
)

comparacao_casa_fora = vitorias_casa.join(vitorias_fora, how="inner")

comparacao_casa_fora["%_vit_casa"] = (
    comparacao_casa_fora["vitorias_casa"] /
    comparacao_casa_fora["jogos_casa"] * 100
)

comparacao_casa_fora["%_vit__fora"] = (
    comparacao_casa_fora["vitorias_fora"] /
    comparacao_casa_fora["jogos_fora"] * 100
)

comparacao_casa_fora["diferenca"] = (
    comparacao_casa_fora["%_vit_casa"] -
    comparacao_casa_fora["%_vit__fora"]
)

comparacao_casa_fora[["%_vit_casa", "%_vit__fora", "diferenca"]] = (
    comparacao_casa_fora[["%_vit_casa", "%_vit__fora", "diferenca"]].round(2)
)

comparacao_casa_fora.sort_values("diferenca", ascending=False)

,jogos_casa,vitorias_casa,jogos_fora,vitorias_fora,%_vit_casa,%_vit__fora,diferenca
mandante,,,,,,,
Ponte Preta,57,31,57,7,54.39,12.28,42.11
Bahia,133,66,133,23,49.62,17.29,32.33
Internacional,171,98,171,43,57.31,25.15,32.16
Athletico-PR,171,96,171,41,56.14,23.98,32.16
Mirassol,19,12,19,6,63.16,31.58,31.58
Santa Cruz,19,7,19,1,36.84,5.26,31.58
Santos,190,105,190,46,55.26,24.21,31.05
Gremio,171,100,171,49,58.48,28.65,29.82
Atletico-MG,190,114,189,60,60.00,31.75,28.25
Fluminense,190,102,190,49,53.68,25.79,27.89
America-MG,95,38,95,12,40.00,12.63,27.37
Joinville,19,6,19,1,31.58,5.26,26.32
Sao Paulo,190,98,190,50,51.58,26.32,25.26
Corinthians,190,101,190,54,53.16,28.42,24.74
Figueirense,38,14,38,5,36.84,13.16,23.68
Palmeiras,190,123,190,80,64.74,42.11,22.63
Sport,133,52,133,22,39.10,16.54,22.56
Bragantino,95,45,95,24,47.37,25.26,22.11
Fortaleza,114,54,114,29,47.37,25.44,21.93
CSA,19,6,19,2,31.58,10.53,21.05
Flamengo,190,120,190,81,63.16,42.63,20.53
Ceara,114,43,114,20,37.72,17.54,20.18
Coritiba,114,41,114,19,35.96,16.67,19.30
Juventude,57,17,57,6,29.82,10.53,19.30
Chapecoense,113,40,114,19,35.40,16.67,18.73
Vasco,133,53,133,29,39.85,21.80,18.05
Cruzeiro,133,59,133,36,44.36,27.07,17.29
Botafogo-RJ,152,69,152,43,45.39,28.29,17.11
Goias,95,35,95,19,36.84,20.00,16.84
Vitoria,76,27,76,16,35.53,21.05,14.47
Avai,76,21,76,12,27.63,15.79,11.84
Parana,19,3,19,1,15.79,5.26,10.53
Cuiaba,57,19,57,15,33.33,26.32,7.02
Atletico-GO,76,22,76,20,28.95,26.32,2.63

In [88]:
df_analise["chutes_total"] = (
    df_analise["chutes_mandante"] +
    df_analise["chutes_visitante"]
)

df_analise["gols_total"] = (
    df_analise["gols_mandante"] +
    df_analise["gols_visitante"]
)

finalizacoes_gols = (
    df_analise.groupby("gols_total")["chutes_total"]
    .agg(["count", "mean"])
    .round(2)
)

finalizacoes_gols

            count   mean
gols_total
0             329  24.10
1             876  24.16
2             967  25.10
3             838  26.00
4             450  26.55
5             198  27.32
6              90  28.02
7              35  30.03
8              13  27.69
9               2  29.00
10              1  35.00

In [89]:
times_casa = df_analise[ ["mandante", "gols_mandante", "chutes_mandante"]].copy()
times_casa.columns = ["time", "gols", "chutes"]

times_fora = df_analise[["visitante", "gols_visitante", "chutes_visitante"]].copy()
times_fora.columns = ["time", "gols", "chutes"]

dados_times = pd.concat([times_casa, times_fora], ignore_index=True)

dados_times.head()

          time  gols  chutes
0  Chapecoense     2      13
1    Palmeiras     2      17
2   Fluminense     1      26
3       Gremio     3      11
4     Cruzeiro     0      13

In [90]:
dados_times.shape

(7598, 3)

In [91]:
estatisticas_times = (
    dados_times
    .groupby("time")
    .agg(
        jogos=("time", "count"),
        gols=("gols", "sum"),
        chutes=("chutes", "sum")
    )
)

estatisticas_times.head()

              jogos  gols  chutes
time
America-MG      190   176    2479
Athletico-PR    342   409    4159
Atletico-GO     152   150    1877
Atletico-MG     379   550    5343
Avai            152   119    1750

In [92]:
estatisticas_times.shape

(34, 3)

In [93]:
estatisticas_times["media_gols"] = (
    estatisticas_times["gols"] /
    estatisticas_times["jogos"]
)

In [94]:
estatisticas_times["media_chutes"] = (
    estatisticas_times["chutes"] /
    estatisticas_times["jogos"]
)

In [95]:
estatisticas_times["eficiencia_conversao"] = (
    estatisticas_times["gols"] /
    estatisticas_times["chutes"] * 100
)

In [96]:
top_media_gols = (
    estatisticas_times
    .sort_values("media_gols", ascending=False)
    [["jogos", "gols", "media_gols"]]
    .head(10)
)

print("TOP 10 - MAIOR MÉDIA DE GOLS POR PARTIDA")
print(top_media_gols)

TOP 10 - MAIOR MÉDIA DE GOLS POR PARTIDA
               jogos  gols  media_gols
time
Mirassol          38    63    1.657895
Flamengo         380   622    1.636842
Palmeiras        380   613    1.613158
Atletico-MG      379   550    1.451187
Gremio           342   467    1.365497
Bragantino       190   248    1.305263
Santos           380   481    1.265789
Internacional    342   422    1.233918
Corinthians      380   463    1.218421
Fluminense       380   462    1.215789

In [97]:
top_media_chutes = (
    estatisticas_times
    .sort_values("media_chutes", ascending=False)
    [["jogos", "chutes", "media_chutes"]]
    .head(10)
)

print("TOP 10 - MAIOR MÉDIA DE CHUTES POR PARTIDA")
print(top_media_chutes)

TOP 10 - MAIOR MÉDIA DE CHUTES POR PARTIDA
             jogos  chutes  media_chutes
time
Palmeiras      380    5508     14.494737
Flamengo       380    5501     14.476316
Bragantino     190    2711     14.268421
Atletico-MG    379    5343     14.097625
Cruzeiro       266    3586     13.481203
Bahia          266    3518     13.225564
America-MG     190    2479     13.047368
Gremio         342    4441     12.985380
Sao Paulo      380    4837     12.728947
Fortaleza      228    2900     12.719298

In [98]:
top_eficiencia = (
    estatisticas_times
    .sort_values("eficiencia_conversao", ascending=False)
    [["jogos", "gols", "chutes", "eficiencia_conversao"]]
    .head(10)
)

print("TOP 10 - MAIOR EFICIÊNCIA DE CONVERSÃO")
print(top_eficiencia)

TOP 10 - MAIOR EFICIÊNCIA DE CONVERSÃO
               jogos  gols  chutes  eficiencia_conversao
time
Mirassol          38    63     446             14.125561
Flamengo         380   622    5501             11.307035
Palmeiras        380   613    5508             11.129267
Gremio           342   467    4441             10.515650
Atletico-MG      379   550    5343             10.293842
Corinthians      380   463    4507             10.272909
Santos           380   481    4759             10.107165
Santa Cruz        38    45     451              9.977827
Athletico-PR     342   409    4159              9.834095
Internacional    342   422    4296              9.823091

In [99]:
top_media_gols = top_media_gols.round(2)
top_media_chutes = top_media_chutes.round(2)
top_eficiencia = top_eficiencia.round(2)

In [100]:
df_analise["mais_escanteios"] = df_analise.apply(
    lambda x: "Mandante" if x["escanteios_mandante"] > x["escanteios_visitante"]
    else "Visitante" if x["escanteios_visitante"] > x["escanteios_mandante"]
    else "Empate",
    axis=1
)

print(df_analise["mais_escanteios"].value_counts())

mais_escanteios
Mandante     2167
Visitante    1277
Empate        355
Name: count, dtype: int64

In [101]:
tabela_escanteios = pd.crosstab(
    df_analise["mais_escanteios"],
    df_analise["resultado"]
)

print(tabela_escanteios)

resultado        Empate  Vitória mandante  Vitória visitante
mais_escanteios
Empate              103               172                 80
Mandante            600               967                600
Visitante           319               698                260

In [102]:
tabela_escanteios_pct = pd.crosstab(
    df_analise["mais_escanteios"],
    df_analise["resultado"],
    normalize="index"
) * 100

print(tabela_escanteios_pct.round(2))

resultado        Empate  Vitória mandante  Vitória visitante
mais_escanteios
Empate            29.01             48.45              22.54
Mandante          27.69             44.62              27.69
Visitante         24.98             54.66              20.36

In [103]:
df_analise["mais_chutes"] = df_analise.apply(
    lambda x: "Mandante" if x["chutes_mandante"] > x["chutes_visitante"]
    else "Visitante" if x["chutes_visitante"] > x["chutes_mandante"]
    else "Empate",
    axis=1
)

print(df_analise["mais_chutes"].value_counts())

mais_chutes
Mandante     2450
Visitante    1162
Empate        187
Name: count, dtype: int64

In [104]:
tabela_chutes_pct = pd.crosstab(
    df_analise["mais_chutes"],
    df_analise["resultado"],
    normalize="index"
) * 100

print(tabela_chutes_pct.round(2))

resultado    Empate  Vitória mandante  Vitória visitante
mais_chutes
Empate        25.13             49.73              25.13
Mandante      27.02             49.18              23.80
Visitante     26.94             46.39              26.68

In [105]:
df_analise["eficiencia_mandante"] = (
    df_analise["gols_mandante"] /
    df_analise["chutes_mandante"].replace(0, pd.NA)
) * 100

df_analise["eficiencia_visitante"] = (
    df_analise["gols_visitante"] /
    df_analise["chutes_visitante"].replace(0, pd.NA)
) * 100

In [106]:
df_analise["mais_eficiente"] = df_analise.apply(
    lambda x: "Sem dados" if pd.isna(x["eficiencia_mandante"]) or pd.isna(x["eficiencia_visitante"])
    else "Mandante" if x["eficiencia_mandante"] > x["eficiencia_visitante"]
    else "Visitante" if x["eficiencia_visitante"] > x["eficiencia_mandante"]
    else "Empate",
    axis=1
)

print(df_analise["mais_eficiente"].value_counts())

mais_eficiente
Mandante     1915
Visitante    1494
Empate        365
Sem dados      25
Name: count, dtype: int64

In [107]:
tabela_eficiencia_pct = pd.crosstab(
    df_analise["mais_eficiente"],
    df_analise["resultado"],
    normalize="index"
) * 100

print(tabela_eficiencia_pct.round(2))

resultado       Empate  Vitória mandante  Vitória visitante
mais_eficiente
Empate           95.89              3.84               0.27
Mandante         11.23             87.62               1.15
Sem dados        28.00             36.00              36.00
Visitante        30.12              9.10              60.78